const $=s=>document.querySelector(s), app=$('#app');
let state={test:null,questions:[],answers:{},started:null,submitted:false,timer:null,mode:'test'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const getHistory=()=>JSON.parse(localStorage.getItem('paesHistoryV2')||'[]');
const saveHistory=h=>localStorage.setItem('paesHistoryV2',JSON.stringify(h.slice(0,100)));
const pct=(a,b)=>b?Math.round(a/b*100):0;
const isExamMode=m=>m==='test'||m==='generated';
function resetState(){clearInterval(state.timer);state={test:null,questions:[],answers:{},started:null,submitted:false,timer:null,mode:'test'}}
function aggregate(records){let a={ok:0,n:0};records.forEach(r=>{a.ok+=r.ok||0;a.n+=r.n||0});return a}
function latestByTest(){let h=getHistory(),m={};h.forEach(x=>{if(!m[x.id]&&isExamMode(x.mode))m[x.id]=x});return m}
function home(){resetState();let latest=latestByTest(),scores=Object.values(latest).map(x=>x.score).filter(Number.isFinite),avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null;app.innerHTML=`
<section class="hero"><div class="heroMain"><div class="eyebrow">Tu centro de entrenamiento PAES</div><h1>Practica. Mide. Mejora.</h1><p>Ensayos completos, práctica focalizada y un diagnóstico que transforma tus resultados en prioridades concretas de estudio.</p><div class="heroActions"><button class="btn" onclick="practiceSetup()">Modo práctica</button><button class="secondary" onclick="diagnostic()">Ver diagnóstico</button></div></div><div class="heroSide"><div class="eyebrow">Promedio últimos ensayos</div><div class="score">${avg??'--'}</div><p>${scores.length?`${scores.length} prueba(s) con resultado registrado.`:'Completa tu primer ensayo para activar el diagnóstico.'}</p><button class="ghost" onclick="history()">Ver historial completo</button></div></section>
<div class="sectionTitle"><div><h2>Ensayos completos</h2><p>Simulación con tiempo, corrección y revisión.</p></div></div><section class="grid">${PAES_DATA.map(t=>{let l=latest[t.id];return `<article class="card"><h2>${esc(t.title)}</h2><div class="meta"><span class="pill">${t.questions.length} preguntas</span><span class="pill">${t.scoredCount} puntuadas</span><span class="pill">${t.minutes} min</span></div>${l?`<p class="tiny">Último resultado: <b>${l.score} pts</b> · ${l.correct}/${l.scored} correctas</p>`:''}<div class="toolbar compact"><button class="btn" onclick="startTest('${t.id}')">Ensayo base</button><button class="secondary" onclick="startGenerated('${t.id}')">✨ Crear ensayo nuevo</button></div></article>`}).join('')}</section>
<div class="sectionTitle"><div><h2>Generador de nuevos ensayos</h2><p>Crea una prueba híbrida distinta combinando preguntas del banco y variantes nuevas controladas. Intenta evitar repeticiones del banco.</p></div></div><section class="card generatorCallout"><div><h3>✨ Ensayo nuevo en un clic</h3><p>Usa 50% de variantes nuevas y 50% del banco validado, conservando la cantidad de preguntas y preguntas puntuadas de cada prueba.</p></div><button class="btn" onclick="generatorSetup()">Crear ensayo nuevo</button></section><div class="sectionTitle"><div><h2>Herramientas V2</h2><p>Entrena con foco y observa patrones.</p></div></div><section class="grid three"><article class="card"><h3>🎯 Práctica focalizada</h3><p>Filtra por prueba, eje/habilidad y dificultad. También puedes repetir tus errores.</p><button class="secondary" onclick="practiceSetup()">Configurar práctica</button></article><article class="card"><h3>🧠 Diagnóstico</h3><p>Fortalezas, prioridades, dominio por contenido y evolución por dificultad.</p><button class="secondary" onclick="diagnostic()">Abrir diagnóstico</button></article><article class="card"><h3>📈 Historial</h3><p>Compara puntajes, porcentaje de aciertos y tiempo utilizado.</p><button class="secondary" onclick="history()">Ver progreso</button></article></section>`}

function generatorSetup(){resetState();app.innerHTML=`<h1>Crear ensayo nuevo</h1><p>El generador híbrido crea una versión distinta manteniendo la estructura de la prueba seleccionada.</p><section class="card"><div class="setup"><div class="field"><label>Prueba</label><select id="gtest">${PAES_DATA.map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('')}</select></div><div class="field"><label>Proporción de variantes nuevas</label><select id="gratio"><option value="0.35">35% nuevas</option><option value="0.5" selected>50% nuevas</option><option value="0.65">65% nuevas</option></select></div></div><div class="notice"><b>Cómo funciona:</b> las variantes se generan con plantillas controladas y el resto se selecciona del banco intentando no repetir preguntas ya usadas. No requiere una clave de IA y funciona sin conexión después de cargar la app.</div><div class="toolbar"><button class="btn" onclick="startGenerated($('#gtest').value,+$('#gratio').value)">✨ Generar y comenzar</button><button class="secondary" onclick="home()">Volver</button></div></section><section class="card"><h3>IA futura preparada de forma segura</h3><p class="tiny">Para usar un modelo externo en producción, la clave debe vivir en un backend/función segura, nunca dentro de app.js. Esta V2 final funciona completa sin esa dependencia.</p></section>`}
function startGenerated(id,ratio=0.5){let t=PAES_GENERATOR.createHybridExam(id,ratio);state={test:t,questions:t.questions,answers:{},started:Date.now(),submitted:false,timer:null,mode:'generated'};renderQuiz();state.timer=setInterval(updateTimer,1000);window.scrollTo(0,0)}

function startTest(id){let t=PAES_DATA.find(x=>x.id===id);state={test:t,questions:t.questions,answers:{},started:Date.now(),submitted:false,timer:null,mode:'test'};renderQuiz();state.timer=setInterval(updateTimer,1000);window.scrollTo(0,0)}
function updateTimer(){const el=$('#timer');if(!el||!state.started)return;let total=isExamMode(state.mode)?state.test.minutes*60:Math.max(15,state.questions.length*2)*60,left=Math.max(0,total-Math.floor((Date.now()-state.started)/1000));el.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left===0){clearInterval(state.timer);submitCurrent()}}
function reading(){if(!state.test?.readingTexts?.length)return'';return `<details class="passage"><summary><b>Ver textos de lectura</b></summary>${state.test.readingTexts.map(x=>`<h3>Texto ${x.n}: ${esc(x.title)}</h3><p>${esc(x.body)}</p>`).join('')}</details>`}
function renderQuiz(){let title=isExamMode(state.mode)?state.test.title:`Práctica - ${state.test.title}`;app.innerHTML=`<div class="quiztop"><button class="secondary" onclick="home()">← Salir</button><div class="progress"><div id="bar"></div></div><b id="timer">--:--</b></div><h1>${esc(title)}</h1>${reading()}<div id="questions">${state.questions.map((q,i)=>`<section class="question" id="q${i}"><div class="meta"><span class="pill">Pregunta ${i+1}</span><span class="pill">${esc(q.difficulty||'Referencial')}</span><span class="pill">${esc(q.skill||'General')}</span>${q.source?`<span class="pill source">${esc(q.source)}</span>`:''}${q.scored?'':'<span class="pill">Piloto / no puntuada</span>'}</div>${q.context?`<div class="passage inlinePassage"><b>Texto para esta pregunta</b><p>${esc(q.context)}</p></div>`:''}<h3>${esc(q.text)}</h3>${q.options.map(o=>`<label class="option"><input type="radio" name="q${i}" value="${o.key}" onchange="answer(${i},'${o.key}')"><b>${o.key})</b> ${esc(o.text)}</label>`).join('')}</section>`).join('')}</div><div class="toolbar"><button class="btn" onclick="submitCurrent()">Finalizar y corregir</button><button class="secondary" onclick="window.scrollTo(0,0)">Ir arriba</button></div>`;updateTimer();updateProgress()}
function answer(i,k){state.answers[i]=k;updateProgress()}
function updateProgress(){let b=$('#bar');if(b)b.style.width=(100*Object.keys(state.answers).length/state.questions.length)+'%'}
function scoreEstimate(correct,t){let r=t.scoreRanges.find(x=>correct>=x[0]&&correct<=x[1])||t.scoreRanges[t.scoreRanges.length-1],[a,b,s1,s2,level]=r;return {score:a===b?s2:Math.round(s1+(correct-a)/(b-a)*(s2-s1)),level}}
function breakdown(questions){let skills={},diff={};questions.forEach((q,i)=>{if(!q.scored)return;let ok=state.answers[i]===q.answer;for(const [obj,key] of [[skills,q.skill||'General'],[diff,q.difficulty||'Referencial']]){obj[key]??={ok:0,n:0};obj[key].n++;if(ok)obj[key].ok++}});return {skills,diff}}
function submitCurrent(){if(!state.test||state.submitted)return;clearInterval(state.timer);state.submitted=true;let scored=state.questions.filter(q=>q.scored),correct=state.questions.filter((q,i)=>q.scored&&state.answers[i]===q.answer).length,answered=Object.keys(state.answers).length,elapsed=Math.max(1,Math.round((Date.now()-state.started)/60000)),bd=breakdown(state.questions),est=isExamMode(state.mode)?scoreEstimate(correct,state.test):{score:null,level:practiceLevel(pct(correct,scored.length))};let wrongItems=state.questions.map((q,i)=>({q,i})).filter(x=>x.q.scored&&state.answers[x.i]!==x.q.answer);let wrong=wrongItems.map(x=>x.q.n);let wrongQuestions=wrongItems.map(x=>x.q.source==='Generada'?x.q:null).filter(Boolean);let rec={date:new Date().toISOString(),id:state.test.id,title:state.test.title,mode:state.mode,correct,scored:scored.length,score:est.score,level:est.level,elapsed,skills:bd.skills,difficulty:bd.diff,wrong,wrongQuestions,generatedCount:state.test.generatedCount||0,bankCount:state.test.bankCount||0};let h=getHistory();h.unshift(rec);saveHistory(h);renderResults(rec)}
function practiceLevel(p){return p>=85?'Dominado':p>=65?'En desarrollo':'Prioridad de estudio'}
function renderBars(obj){return Object.entries(obj).sort((a,b)=>pct(b[1].ok,b[1].n)-pct(a[1].ok,a[1].n)).map(([k,v])=>`<div class="barRow"><b>${esc(k)}</b><div class="barTrack"><div class="barFill" style="width:${pct(v.ok,v.n)}%"></div></div><span>${pct(v.ok,v.n)}%</span></div>`).join('')}
function renderResults(r){let p=pct(r.correct,r.scored);app.innerHTML=`<h1>Resultados - ${esc(r.title)}</h1><section class="resultbox"><div class="kpis"><div class="kpi">${isExamMode(r.mode)?'Puntaje estimado':'Rendimiento'}<b class="score">${isExamMode(r.mode)?r.score:p+'%'}</b>${esc(r.level)}</div><div class="kpi">Correctas<b>${r.correct}/${r.scored}</b>${p}%</div><div class="kpi">Respondidas<b>${Object.keys(state.answers).length}/${state.questions.length}</b></div><div class="kpi">Tiempo usado<b>${r.elapsed} min</b></div></div>${r.mode==='generated'?`<p class="tiny"><b>Ensayo híbrido:</b> ${r.generatedCount} variantes generadas + ${r.bankCount} preguntas del banco.</p>`:''}<p class="tiny">Puntajes y niveles son aproximaciones de estudio; no reemplazan la escala oficial de cada aplicación PAES.</p></section><div class="sectionTitle"><div><h2>Desempeño por eje/habilidad</h2></div></div><section class="card">${renderBars(r.skills)}</section><div class="sectionTitle"><div><h2>Por dificultad</h2></div></div><section class="card">${renderBars(r.difficulty)}</section><div class="toolbar"><button class="btn" onclick="review()">Revisar respuestas</button><button class="secondary" onclick="diagnostic()">Ver diagnóstico acumulado</button><button class="ghost" onclick="home()">Inicio</button></div>`;window.scrollTo(0,0)}
function review(){let t=state.test;app.innerHTML=`<h1>Revisión - ${esc(t.title)}</h1><div class="toolbar"><button class="secondary" onclick="home()">Inicio</button><button class="ghost" onclick="practiceWrong('${t.id}')">Practicar errores</button></div>${state.questions.map((q,i)=>{let mine=state.answers[i],ok=mine===q.answer;return `<section class="question"><div class="meta"><span class="pill">Pregunta ${i+1}</span><span class="pill">${esc(q.difficulty||'')}</span><span class="pill">${esc(q.skill||'')}</span>${q.source?`<span class="pill source">${esc(q.source)}</span>`:''}</div>${q.context?`<div class="passage inlinePassage"><b>Texto para esta pregunta</b><p>${esc(q.context)}</p></div>`:''}<h3>${esc(q.text)}</h3>${q.options.map(o=>`<div class="option ${o.key===q.answer?'correct':(o.key===mine&&!ok?'wrong':'')}"><b>${o.key})</b> ${esc(o.text)}</div>`).join('')}<div class="explain"><b>${ok?'Correcta':'Tu respuesta: '+(mine||'Sin responder')+' · Correcta: '+q.answer}</b><br>${esc(q.explanation)}</div></section>`}).join('')}`;window.scrollTo(0,0)}
function allSkillsFor(id){let t=PAES_DATA.find(x=>x.id===id);return [...new Set(t.questions.map(q=>q.skill||'General'))].sort()}
function practiceSetup(){resetState();app.innerHTML=`<h1>Práctica focalizada</h1><p>Configura una sesión corta para reforzar exactamente lo que necesitas.</p><section class="card"><div class="setup"><div class="field"><label>Prueba</label><select id="ptest" onchange="refreshSkillOptions()">${PAES_DATA.map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('')}</select></div><div class="field"><label>Eje / habilidad</label><select id="pskill"></select></div><div class="field"><label>Dificultad</label><select id="pdiff"><option value="all">Todas</option><option>Fácil</option><option>Media</option><option>Difícil</option></select></div><div class="field"><label>Cantidad</label><select id="pcount"><option>5</option><option selected>10</option><option>15</option><option>20</option></select></div></div><div class="toolbar"><button class="btn" onclick="startPractice()">Comenzar práctica</button><button class="secondary" onclick="home()">Volver</button></div></section><div class="sectionTitle"><div><h2>Atajos</h2></div></div><section class="grid">${PAES_DATA.map(t=>`<article class="card"><h3>${esc(t.title)}</h3><p>Repite preguntas que hayas fallado previamente.</p><button class="ghost" onclick="practiceWrong('${t.id}')">Practicar mis errores</button></article>`).join('')}</section>`;refreshSkillOptions()}
function refreshSkillOptions(){let id=$('#ptest')?.value||PAES_DATA[0].id,el=$('#pskill');if(el)el.innerHTML='<option value="all">Todos</option>'+allSkillsFor(id).map(s=>`<option>${esc(s)}</option>`).join('')}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
function startPractice(){let id=$('#ptest').value,skill=$('#pskill').value,diff=$('#pdiff').value,count=+$(`#pcount`).value,t=PAES_DATA.find(x=>x.id===id),qs=t.questions.filter(q=>(skill==='all'||q.skill===skill)&&(diff==='all'||q.difficulty===diff));if(!qs.length){alert('No hay preguntas con esa combinación. Prueba otro filtro.');return}qs=shuffled(qs).slice(0,count);state={test:t,questions:qs,answers:{},started:Date.now(),submitted:false,timer:null,mode:'practice'};renderQuiz();state.timer=setInterval(updateTimer,1000);window.scrollTo(0,0)}
function practiceWrong(id){let h=getHistory().filter(x=>x.id===id&&((x.wrong?.length)||(x.wrongQuestions?.length))),nums=[...new Set(h.flatMap(x=>x.wrong||[]).map(String))],t=PAES_DATA.find(x=>x.id===id),bank=t.questions.filter(q=>nums.includes(String(q.n))),generated=h.flatMap(x=>x.wrongQuestions||[]),seen=new Set(),genUnique=generated.filter(q=>{let k=q.id||q.text;if(seen.has(k))return false;seen.add(k);return true}),qs=[...bank,...genUnique];if(!qs.length){alert('Aún no tienes errores registrados en esta prueba. Completa un ensayo o práctica primero.');return}state={test:t,questions:shuffled(qs).slice(0,20),answers:{},started:Date.now(),submitted:false,timer:null,mode:'practice'};renderQuiz();state.timer=setInterval(updateTimer,1000);window.scrollTo(0,0)}
function history(){resetState();let h=getHistory();app.innerHTML=`<h1>Historial</h1><div class="card">${h.length?h.map(x=>`<div class="historyrow"><div><b>${esc(x.title)}</b><br><small>${new Date(x.date).toLocaleString('es-CL')} · ${isExamMode(x.mode)?(x.mode==='generated'?'Ensayo generado':'Ensayo base'):'Práctica'}</small></div><b>${isExamMode(x.mode)?x.score+' pts':pct(x.correct,x.scored)+'%'}</b><span>${x.correct}/${x.scored} · ${esc(x.level)}</span></div>`).join(''):'<div class="empty">Aún no hay sesiones finalizadas.</div>'}</div><div class="toolbar"><button class="secondary" onclick="home()">Volver</button>${h.length?'<button class="danger" onclick="clearHistory()">Borrar historial</button>':''}</div>`}
function clearHistory(){if(confirm('¿Seguro que quieres borrar todo el historial y diagnóstico?')){localStorage.removeItem('paesHistoryV2');history()}}
function diagnostic(){resetState();let h=getHistory();if(!h.length){app.innerHTML=`<h1>Diagnóstico</h1><section class="card empty"><h2>Aún no hay datos suficientes</h2><p>Completa al menos un ensayo o práctica para activar fortalezas, prioridades y recomendaciones.</p><button class="btn" onclick="home()">Elegir ensayo</button></section>`;return}
let tests=h.filter(x=>isExamMode(x.mode)),sessions=h,skills={},diff={};sessions.forEach(r=>{Object.entries(r.skills||{}).forEach(([k,v])=>{skills[k]??={ok:0,n:0};skills[k].ok+=v.ok;skills[k].n+=v.n});Object.entries(r.difficulty||{}).forEach(([k,v])=>{diff[k]??={ok:0,n:0};diff[k].ok+=v.ok;diff[k].n+=v.n})});let ordered=Object.entries(skills).sort((a,b)=>pct(a[1].ok,a[1].n)-pct(b[1].ok,b[1].n)),priority=ordered.slice(0,3),strength=[...ordered].reverse().slice(0,3),avg=tests.length?Math.round(tests.reduce((a,b)=>a+b.score,0)/tests.length):null,trend=tests.slice(0,10).reverse();let recs=priority.map(([k,v])=>{let p=pct(v.ok,v.n),qty=p<50?20:p<65?15:10;return `<div class="recommend"><strong>${p<60?'🔴':'🟡'} ${esc(k)} · ${p}%</strong>Realiza ${qty} preguntas focalizadas de este eje, revisa cada error y repite el bloque hasta superar 70%.</div>`}).join('');
app.innerHTML=`<h1>Diagnóstico acumulado</h1><section class="resultbox"><div class="kpis"><div class="kpi">Promedio ensayos<b>${avg??'--'}${avg?' pts':''}</b></div><div class="kpi">Sesiones registradas<b>${sessions.length}</b></div><div class="kpi">Mejor fortaleza<b>${strength[0]?esc(strength[0][0]):'--'}</b>${strength[0]?pct(strength[0][1].ok,strength[0][1].n)+'%':''}</div><div class="kpi">Prioridad principal<b>${priority[0]?esc(priority[0][0]):'--'}</b>${priority[0]?pct(priority[0][1].ok,priority[0][1].n)+'%':''}</div></div></section>
<div class="sectionTitle"><div><h2>Semáforo de dominio</h2><p>🟢 80%+ · 🟡 60-79% · 🔴 menos de 60%</p></div></div><section class="mastery">${ordered.map(([k,v])=>{let p=pct(v.ok,v.n),c=p>=80?'g':p>=60?'y':'r';return `<div class="${c}"><b>${p>=80?'🟢':p>=60?'🟡':'🔴'} ${esc(k)}</b><div class="score" style="font-size:28px">${p}%</div><span class="tiny">${v.ok}/${v.n} correctas acumuladas</span></div>`}).join('')}</section>
<div class="sectionTitle"><div><h2>Plan recomendado</h2><p>Prioridades calculadas según tus resultados acumulados.</p></div></div>${recs||'<section class="card">Sin prioridades detectadas.</section>'}
<div class="sectionTitle"><div><h2>Rendimiento por dificultad</h2></div></div><section class="card">${renderBars(diff)}</section>
<div class="sectionTitle"><div><h2>Evolución de ensayos</h2><p>${trend.length?'Últimos '+trend.length+' ensayos completos':'Completa ensayos completos para ver puntajes.'}</p></div></div><section class="card">${trend.length?`<div class="trend">${trend.map(x=>`<i style="height:${Math.max(8,(x.score-100)/9)}%" title="${x.score} pts"></i>`).join('')}</div><div class="tiny" style="margin-top:8px">${trend.map(x=>x.score).join(' → ')} pts</div>`:'<div class="empty">Sin ensayos completos registrados.</div>'}</section>
<div class="sectionTitle"><div><h2>Fortalezas actuales</h2></div></div><section class="grid three">${strength.map(([k,v])=>`<article class="card"><h3>🟢 ${esc(k)}</h3><div class="score" style="font-size:34px">${pct(v.ok,v.n)}%</div><p class="tiny">Mantén el dominio incorporando preguntas difíciles.</p></article>`).join('')}</section><div class="toolbar"><button class="btn" onclick="practiceSetup()">Entrenar una prioridad</button><button class="secondary" onclick="home()">Inicio</button></div>`;window.scrollTo(0,0)}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});home();
