const $=s=>document.querySelector(s), app=$('#app');
let state={test:null,questions:[],answers:{},started:null,submitted:false,timer:null,mode:'test'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const PROFILES_KEY='paesProfilesV2', ACTIVE_KEY='paesActiveProfileV2';
const safeParse=(v,fallback)=>{try{return JSON.parse(v)||fallback}catch{return fallback}};
const getProfiles=()=>safeParse(localStorage.getItem(PROFILES_KEY),[]);
const saveProfiles=p=>localStorage.setItem(PROFILES_KEY,JSON.stringify(p));
const getActiveId=()=>localStorage.getItem(ACTIVE_KEY)||'';
const setActiveId=id=>{localStorage.setItem(ACTIVE_KEY,id);window.PAES_PROFILE_SCOPE=id||'none'};
const getActiveProfile=()=>getProfiles().find(p=>p.id===getActiveId())||null;
const scopedKey=(base,id=getActiveId())=>`${base}_${id||'none'}`;
// ===== GAMIFICACION / RACHA =====
const GAME_KEY='paesGameV1';
const chileDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dateDiff=(a,b)=>Math.round((new Date(b+'T12:00:00Z')-new Date(a+'T12:00:00Z'))/86400000);
const weekKey=(d=chileDate())=>{let x=new Date(d+'T12:00:00Z'),day=(x.getUTCDay()+6)%7;x.setUTCDate(x.getUTCDate()-day);return x.toISOString().slice(0,10)};
const gameDefault=()=>({xp:0,streak:0,bestStreak:0,lastActiveDate:'',freezeCount:0,badges:[],claimed:{},daily:{date:'',missionKey:'',progress:0,claimed:false},weekly:{key:'',practices:0,exams:0,errorSessions:0,studyDays:[],claimed:false},updatedAt:new Date().toISOString()});
function getGame(){let g=safeParse(localStorage.getItem(scopedKey(GAME_KEY)),null);return {...gameDefault(),...(g||{}),claimed:{...(g?.claimed||{})},daily:{...gameDefault().daily,...(g?.daily||{})},weekly:{...gameDefault().weekly,...(g?.weekly||{})}}}
function saveGame(g){g.updatedAt=new Date().toISOString();localStorage.setItem(scopedKey(GAME_KEY),JSON.stringify(g));syncGamification(g).catch(()=>{});return g}
const GAME_LEVELS=[['🌱 Aspirante',0],['🚀 En marcha',500],['⚡ Competidor',1500],['🔥 Imparable',3000],['🏆 Experto PAES',6000],['👑 Leyenda PAES',10000]];
function gameLevel(g=getGame()){let cur=GAME_LEVELS[0],next=null;GAME_LEVELS.forEach((x,i)=>{if(g.xp>=x[1])cur=x;else if(!next)next=x});return {name:cur[0],min:cur[1],next}}
function weakestSkill(){let h=getHistory(),skills={};h.forEach(r=>Object.entries(r.skills||{}).forEach(([k,v])=>{skills[k]??={ok:0,n:0};skills[k].ok+=v.ok;skills[k].n+=v.n}));let items=Object.entries(skills).filter(([,v])=>v.n>=2).sort((a,b)=>pct(a[1].ok,a[1].n)-pct(b[1].ok,b[1].n));return items[0]?.[0]||'tu prueba prioritaria'}
function dailyMission(g=getGame()){let today=chileDate(),skill=weakestSkill(),key=`${today}|${skill}`;if(g.daily.date!==today||g.daily.missionKey!==key)g.daily={date:today,missionKey:key,skill,progress:0,target:10,claimed:false};return g.daily}
function ensureWeekly(g){let k=weekKey();if(g.weekly.key!==k)g.weekly={key:k,practices:0,exams:0,errorSessions:0,studyDays:[],claimed:false};return g.weekly}
function unlockBadge(g,key,label){if(!g.badges.includes(key)){g.badges.push(key);return label}return null}
function refreshBadges(g){let unlocked=[];if(g.streak>=3)unlocked.push(unlockBadge(g,'streak3','🔥 Primera Racha'));if(g.streak>=7)unlocked.push(unlockBadge(g,'streak7','⚡ Semana en Llamas'));if(g.streak>=30)unlocked.push(unlockBadge(g,'streak30','🏆 Imparable 30'));if(g.streak>=100)unlocked.push(unlockBadge(g,'streak100','👑 Centenario PAES'));if(g.xp>=1500)unlocked.push(unlockBadge(g,'xp1500','⚡ Competidor'));if(g.xp>=6000)unlocked.push(unlockBadge(g,'xp6000','🏆 Experto PAES'));let h=getHistory(),exams=h.filter(x=>isExamMode(x.mode)&&Number.isFinite(x.score));if(exams.some(x=>pct(x.correct,x.scored)>=80))unlocked.push(unlockBadge(g,'accuracy80','🎯 Precisión 80'));if(exams.length>=2){let first=exams[exams.length-1]?.score||0,best=Math.max(...exams.map(x=>x.score||0));if(best-first>=100)unlocked.push(unlockBadge(g,'up100','📈 En ascenso +100'))}return unlocked.filter(Boolean)}
function gamifySession(rec){let g=getGame(),today=chileDate(),answered=Number(rec.answered||0),answeredScored=Number(rec.answeredScored||0),rewards=[];
if(answered===0||answeredScored===0)return {g,rewards};
let minValid=isExamMode(rec.mode)?Math.max(10,Math.ceil(rec.scored*.2)):rec.mode==='errors'?5:Math.min(10,rec.scored),valid=answeredScored>=minValid,base=isExamMode(rec.mode)?Math.max(20,Math.round(250*answeredScored/Math.max(1,rec.scored))):rec.mode==='errors'?Math.max(15,Math.round(75*answeredScored/Math.max(1,rec.scored))):Math.max(10,Math.round(80*answeredScored/Math.max(1,rec.scored))),accuracy=pct(rec.correct,answeredScored),bonus=valid&&accuracy>=80?100:0;
if(valid){g.xp+=base+bonus;rewards.push(`+${base} XP por ${isExamMode(rec.mode)?'ensayo':'práctica'} válida`);if(bonus)rewards.push('+100 XP por 80% o más')}
if(valid&&g.lastActiveDate!==today){if(!g.lastActiveDate){g.streak=1}else{let gap=dateDiff(g.lastActiveDate,today);if(gap===1)g.streak+=1;else if(gap===2&&g.freezeCount>0){g.freezeCount-=1;g.streak+=1;rewards.push('🛡️ Protector usado: tu racha sigue viva')}else if(gap>1)g.streak=1}g.lastActiveDate=today;g.bestStreak=Math.max(g.bestStreak,g.streak);if(g.streak>0&&g.streak%7===0&&g.freezeCount<2){g.freezeCount+=1;rewards.push('🛡️ Ganaste un Protector de Racha')}}
let m=dailyMission(g),missionHits=Number(rec.answeredSkills?.[m.skill]||0);if(valid&&missionHits&&!m.claimed){m.progress=Math.min(m.target,(m.progress||0)+missionHits);if(m.progress>=m.target){m.claimed=true;g.xp+=100;rewards.push('🎯 Misión diaria completa: +100 XP')}}
let w=ensureWeekly(g);if(valid){if(!w.studyDays.includes(today))w.studyDays.push(today);if(isExamMode(rec.mode))w.exams++;else if(rec.mode==='errors')w.errorSessions++;else w.practices++}if(!w.claimed&&w.practices>=3&&w.exams>=1&&w.errorSessions>=1&&w.studyDays.length>=4){w.claimed=true;g.xp+=500;rewards.push('🏆 Desafío semanal completo: +500 XP')}
let badges=valid?refreshBadges(g):[];badges.forEach(x=>rewards.push(`Medalla desbloqueada: ${x}`));if(valid)saveGame(g);return {g,rewards}}
async function syncGamification(g=getGame()){if(commercialMode!=='member'||!currentAccess||!isConfigured())return;let client=await initSupabase();if(!client)return;await client.from('user_gamification').upsert({user_id:currentAccess.user_id,xp:g.xp,streak:g.streak,best_streak:g.bestStreak,last_active_date:g.lastActiveDate||null,freeze_count:g.freezeCount,badges:g.badges,weekly:g.weekly,updated_at:new Date().toISOString()},{onConflict:'user_id'})}
function badgeLabel(key){return ({streak3:'🔥 Primera Racha',streak7:'⚡ Semana en Llamas',streak30:'🏆 Imparable 30',streak100:'👑 Centenario PAES',xp1500:'⚡ Competidor',xp6000:'🏆 Experto PAES',accuracy80:'🎯 Precisión 80',up100:'📈 En ascenso +100'})[key]||key}
function gamePanelHTML(){let g=getGame(),lvl=gameLevel(g),m=dailyMission(g),w=ensureWeekly(g),next=lvl.next,prog=next?Math.max(0,Math.min(100,Math.round((g.xp-lvl.min)/(next[1]-lvl.min)*100))):100;return `<section class="gameHero card"><div class="gameTop"><div><div class="eyebrow">TU RACHA PAES</div><h2>🔥 ${g.streak} día${g.streak===1?'':'s'} · ${lvl.name}</h2><p><b>${g.xp.toLocaleString('es-CL')} XP</b> · Récord ${g.bestStreak} días · 🛡️ ${g.freezeCount} protector${g.freezeCount===1?'':'es'}</p></div><button class="secondary" onclick="gamification()">Ver premios</button></div><div class="xpTrack"><div style="width:${prog}%"></div></div><div class="gameMission"><span>🎯 Misión de hoy</span><b>10 preguntas de ${esc(m.skill)}</b><small>${m.progress||0}/${m.target||10} · Premio +100 XP</small></div><div class="weeklyMini"><span>🏆 Semana: ${w.practices}/3 prácticas · ${w.exams}/1 ensayo · ${w.errorSessions}/1 errores · ${w.studyDays.length}/4 días</span></div></section>`}
function gamification(){resetState();let g=getGame(),lvl=gameLevel(g),m=dailyMission(g),w=ensureWeekly(g),badges=g.badges.map(b=>`<div class="badgeCard"><span>${badgeLabel(b).split(' ')[0]}</span><b>${esc(badgeLabel(b).split(' ').slice(1).join(' '))}</b></div>`).join('');app.innerHTML=`<h1>🔥 Mi Racha PAES</h1><section class="gameProfile card"><div><div class="bigStreak">${g.streak}</div><span>días de racha</span><p>Récord: <b>${g.bestStreak} días</b> · 🛡️ ${g.freezeCount} protectores</p></div><div><div class="eyebrow">NIVEL ACTUAL</div><h2>${lvl.name}</h2><div class="score" style="font-size:36px">${g.xp.toLocaleString('es-CL')} XP</div>${lvl.next?`<p class="tiny">Próximo nivel: ${esc(lvl.next[0])} a ${lvl.next[1].toLocaleString('es-CL')} XP</p>`:'<p class="tiny">Nivel máximo alcanzado.</p>'}</div></section><div class="sectionTitle"><div><h2>🎯 Misión de hoy</h2><p>La misión se adapta a tu diagnóstico.</p></div></div><section class="missionCard card"><h3>Refuerza ${esc(m.skill)}</h3><div class="missionProgress"><div style="width:${Math.min(100,(m.progress||0)/(m.target||10)*100)}%"></div></div><p><b>${m.progress||0}/${m.target||10}</b> preguntas completadas · Premio: <b>+100 XP</b></p><button class="btn" onclick="practiceSetup()">Entrenar ahora</button></section><div class="sectionTitle"><div><h2>🏆 Desafío semanal</h2><p>Completa los cuatro objetivos y gana +500 XP.</p></div></div><section class="card challengeGrid"><div class="${w.practices>=3?'done':''}">${w.practices>=3?'✅':'◯'} 3 prácticas <b>${w.practices}/3</b></div><div class="${w.exams>=1?'done':''}">${w.exams>=1?'✅':'◯'} 1 ensayo <b>${w.exams}/1</b></div><div class="${w.errorSessions>=1?'done':''}">${w.errorSessions>=1?'✅':'◯'} Practicar errores <b>${w.errorSessions}/1</b></div><div class="${w.studyDays.length>=4?'done':''}">${w.studyDays.length>=4?'✅':'◯'} Estudiar 4 días <b>${w.studyDays.length}/4</b></div></section><div class="sectionTitle"><div><h2>🏅 Mis medallas</h2><p>Premios por constancia y progreso personal.</p></div></div><section class="badgesGrid">${badges||'<div class="card empty">Completa actividades para desbloquear tu primera medalla.</div>'}</section><div class="sectionTitle"><div><h2>Próximos premios</h2></div></div><section class="grid three"><article class="card"><h3>🔥 3 días</h3><p>Primera Racha</p></article><article class="card"><h3>⚡ 7 días</h3><p>Semana en Llamas + protector</p></article><article class="card"><h3>🏆 30 días</h3><p>Imparable 30</p></article></section><div class="toolbar"><button class="btn" onclick="home()">Volver al inicio</button></div>`;saveGame(g);window.scrollTo(0,0)}
const getHistory=()=>safeParse(localStorage.getItem(scopedKey('paesHistoryV2')),[]);
const saveHistory=h=>localStorage.setItem(scopedKey('paesHistoryV2'),JSON.stringify(h.slice(0,100)));
const uid=()=>`p_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const STUDY=window.PAES_STUDY_PROFILES||{};
function profileTestIds(p=getActiveProfile()){if(!p)return PAES_DATA.map(t=>t.id);if(p.guest)return PAES_DATA.map(t=>t.id);if(p.studyProfile==='personalizado'&&Array.isArray(p.tests)&&p.tests.length)return p.tests;return (STUDY[p.studyProfile||'completas']?.tests||PAES_DATA.map(t=>t.id));}
function visibleTests(){let ids=new Set(profileTestIds());return PAES_DATA.filter(t=>ids.has(t.id));}
function studyLabel(p=getActiveProfile()){return STUDY[p?.studyProfile||'completas']?.label||'PAES completa'}
function gradeLabel(p=getActiveProfile()){return p?.grade===3?'3° Medio':p?.grade===4?'4° Medio':'Curso pendiente'}
function gradeGate(){let p=getActiveProfile();if(!p)return profileGate();resetState();app.innerHTML=`<section class="profileGate"><div class="profileWelcome"><div class="eyebrow">PERSONALIZA TU PREPARACIÓN</div><h1>¿En qué curso estás?</h1><p>Tu curso adapta las cápsulas y las clases personalizadas. Puedes cambiarlo más adelante sin perder tu progreso.</p></div><div class="grid"><article class="card"><div style="font-size:42px">🌱</div><h2>3° Medio</h2><p>Construye fundamentos, aprende con más apoyo y avanza de forma progresiva hacia la PAES.</p><button class="btn full" onclick="setGrade(3)">Estoy en 3° Medio</button></article><article class="card"><div style="font-size:42px">🚀</div><h2>4° Medio</h2><p>Prioriza rendimiento PAES, integración de contenidos, estrategias de prueba y entrenamiento intensivo.</p><button class="btn full" onclick="setGrade(4)">Estoy en 4° Medio</button></article></div></section>`;window.scrollTo(0,0)}
function setGrade(grade){grade=Number(grade);if(![3,4].includes(grade))return;let p=getActiveProfile();if(!p)return;saveProfiles(getProfiles().map(x=>x.id===p.id?{...x,grade}:x));home()}
function studyOptions(selected='completas'){return Object.entries(STUDY).map(([k,v])=>`<option value="${k}" ${k===selected?'selected':''}>${esc(v.label)}</option>`).join('')}
function testChecks(selected=[]){let set=new Set(selected);return `<div class="testChecks">${PAES_DATA.map(t=>`<label class="checkCard"><input type="checkbox" name="ptestsel" value="${t.id}" ${set.has(t.id)?'checked':''}><span>${esc(t.title)}</span></label>`).join('')}</div>`}
function toggleCustomTests(){let box=$('#customTests'),sel=$('#pstudy');if(box)box.style.display=sel?.value==='personalizado'?'block':'none'}
function selectedCustomTests(){return [...document.querySelectorAll('input[name=ptestsel]:checked')].map(x=>x.value)};
function migrateLegacy(){const legacy=localStorage.getItem('paesHistoryV2');if(!legacy||getProfiles().length)return;const id=uid(),profile={id,name:'Mi perfil',goal:700,studyProfile:'completas',tests:[],guest:false,created:new Date().toISOString()};saveProfiles([profile]);setActiveId(id);localStorage.setItem(scopedKey('paesHistoryV2',id),legacy);localStorage.removeItem('paesHistoryV2')}
function profileGate(){resetState();const profiles=getProfiles();app.innerHTML=`<section class="profileGate"><div class="profileWelcome"><div class="eyebrow">PAES Trainer</div><h1>Tu preparación, tu progreso</h1><p>Crea un perfil para que tus ensayos, diagnóstico y recomendaciones queden separados de los demás estudiantes que usen este dispositivo.</p></div><div class="card"><h2>Entrar a PAES Trainer</h2>${profiles.length?`<div class="profileList">${profiles.filter(p=>!p.guest).map(p=>`<button class="profileChoice" onclick="selectProfile('${p.id}')"><span class="avatar">${esc((p.name||'P')[0].toUpperCase())}</span><span><b>${esc(p.name)}</b><small>${esc(studyLabel(p))} · Meta: ${p.goal||700} pts</small></span><strong>Entrar →</strong></button>`).join('')}</div>`:''}<div class="toolbar"><button class="btn" onclick="createProfileScreen()">+ Crear perfil</button><button class="secondary" onclick="continueGuest()">Continuar como invitado</button></div><p class="tiny">El modo invitado guarda datos solo en este navegador y puede borrarse al cerrar sesión.</p></div></section>`}
function createProfileScreen(){resetState();app.innerHTML=`<h1>Crear perfil</h1><section class="card profileForm"><div class="field"><label>Nombre</label><input id="pname" maxlength="40" placeholder="Ej.: Catalina"></div><div class="field"><label>Meta de puntaje PAES</label><select id="pgoal">${[600,650,700,750,800,850,900,950,1000].map(x=>`<option ${x===750?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Perfil de practica y estudio</label><select id="pstudy" onchange="toggleCustomTests()">${studyOptions('completas')}</select><p class="tiny">El perfil solo organiza tu entrenamiento; no reemplaza los requisitos oficiales de una carrera o universidad.</p></div><div id="customTests" style="display:none"><label>Elige tus pruebas</label>${testChecks(['lectora','m1'])}</div><div class="toolbar"><button class="btn" onclick="createProfile()">Crear y entrar</button><button class="secondary" onclick="profileGate()">Volver</button></div></section>`;setTimeout(()=>$('#pname')?.focus(),0)}
function createProfile(){let name=$('#pname')?.value.trim(),goal=+($('#pgoal')?.value||750),studyProfile=$('#pstudy')?.value||'completas',tests=studyProfile==='personalizado'?selectedCustomTests():[];if(!name){alert('Escribe un nombre para el perfil.');return}if(studyProfile==='personalizado'&&!tests.length){alert('Selecciona al menos una prueba para tu perfil personalizado.');return}let profiles=getProfiles(),id=uid();profiles.push({id,name,goal,studyProfile,tests,guest:false,created:new Date().toISOString()});saveProfiles(profiles);setActiveId(id);home()}
function continueGuest(){let profiles=getProfiles(),guest=profiles.find(p=>p.guest);if(!guest){guest={id:'guest',name:'Invitado',goal:700,studyProfile:'completas',tests:[],guest:true,created:new Date().toISOString()};profiles.push(guest);saveProfiles(profiles)}setActiveId('guest');home()}
function selectProfile(id){if(!getProfiles().some(p=>p.id===id))return;setActiveId(id);home()}
function switchProfile(){setActiveId('');profileGate()}
function editProfile(){let p=getActiveProfile();if(!p||p.guest){alert('El modo invitado no tiene perfil editable.');return}app.innerHTML=`<h1>Mi perfil</h1><section class="card profileForm"><div class="field"><label>Nombre</label><input id="pname" maxlength="40" value="${esc(p.name)}"></div><div class="field"><label>Meta de puntaje PAES</label><select id="pgoal">${[600,650,700,750,800,850,900,950,1000].map(x=>`<option ${x===p.goal?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Curso actual</label><select id="pgrade"><option value="3" ${p.grade===3?'selected':''}>3° Medio</option><option value="4" ${p.grade===4?'selected':''}>4° Medio</option></select><p class="tiny">Cambiar de curso no borra historial, XP, racha ni diagnóstico.</p></div><div class="field"><label>Perfil de practica y estudio</label><select id="pstudy" onchange="toggleCustomTests()">${studyOptions(p.studyProfile||'completas')}</select></div><div id="customTests" style="display:${(p.studyProfile||'completas')==='personalizado'?'block':'none'}"><label>Elige tus pruebas</label>${testChecks(p.tests||[])}</div><div class="toolbar"><button class="btn" onclick="saveProfileSettings()">Guardar cambios</button><button class="secondary" onclick="home()">Cancelar</button></div></section>`}
function saveProfileSettings(){let p=getActiveProfile(),name=$('#pname')?.value.trim(),goal=+$('#pgoal')?.value,grade=+($('#pgrade')?.value||p?.grade||4),studyProfile=$('#pstudy')?.value||'completas',tests=studyProfile==='personalizado'?selectedCustomTests():[];if(!p||!name)return;if(studyProfile==='personalizado'&&!tests.length){alert('Selecciona al menos una prueba.');return}let profiles=getProfiles().map(x=>x.id===p.id?{...x,name,goal,grade,studyProfile,tests}:x);saveProfiles(profiles);home()}
function clearMyData(){let p=getActiveProfile();if(!p)return;if(confirm(`¿Borrar todo el historial, diagnóstico y progreso de ${p.name}?`)){localStorage.removeItem(scopedKey('paesHistoryV2'));localStorage.removeItem(scopedKey('paesUsedBankV2'));home()}}
function deleteProfile(){let p=getActiveProfile();if(!p||p.guest)return;if(confirm(`¿Eliminar el perfil de ${p.name} y todos sus datos? Esta acción no se puede deshacer.`)){localStorage.removeItem(scopedKey('paesHistoryV2'));localStorage.removeItem(scopedKey('paesUsedBankV2'));saveProfiles(getProfiles().filter(x=>x.id!==p.id));setActiveId('');profileGate()}}
function userMenu(){let p=getActiveProfile();if(!p)return '';return `<div class="userChip"><span class="avatar small">${esc((p.name||'P')[0].toUpperCase())}</span><span><b>${esc(p.name)}</b><small>${p.guest?'Modo invitado':`Meta ${p.goal||700}`}</small></span></div>`}
const pct=(a,b)=>b?Math.round(a/b*100):0;
const isExamMode=m=>m==='test'||m==='generated';
function resetState(){clearInterval(state.timer);state={test:null,questions:[],answers:{},started:null,submitted:false,timer:null,mode:'test'}}
function aggregate(records){let a={ok:0,n:0};records.forEach(r=>{a.ok+=r.ok||0;a.n+=r.n||0});return a}
function latestByTest(){let h=getHistory(),m={};h.forEach(x=>{if(!m[x.id]&&isExamMode(x.mode))m[x.id]=x});return m}
function home(){resetState();let profile=getActiveProfile();if(!profile){profileGate();return}if(!profile.grade&&currentAccess?.role!=='admin'){gradeGate();return}window.PAES_PROFILE_SCOPE=profile.id;let tests=visibleTests(),latest=latestByTest(),scores=tests.map(t=>latest[t.id]?.score).filter(Number.isFinite),avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null;app.innerHTML=`${gamePanelHTML()}
<section class="hero"><div class="heroMain"><div class="eyebrow">Tu centro de entrenamiento PAES</div><h1>Hola, ${esc(profile.name)} 👋</h1><h2>${esc(studyLabel(profile))}${profile.grade?` · ${gradeLabel(profile)}`:''}</h2><p>Tu inicio muestra solo las pruebas elegidas para este perfil. Puedes cambiar el perfil de estudio cuando quieras desde Mi perfil.</p><div class="heroActions"><button class="btn" onclick="practiceSetup()">Modo practica</button><button class="secondary" onclick="diagnostic()">Ver diagnostico</button></div></div><div class="heroSide"><div class="eyebrow">Promedio ultimos ensayos</div><div class="score">${avg??'--'}</div><p class="goalLine">Meta personal: <b>${profile.goal||700} pts</b>${avg?` · ${avg>=(profile.goal||700)?'✅ Meta alcanzada':`${Math.max(0,(profile.goal||700)-avg)} pts por avanzar`}`:''}</p><p>${scores.length?`${scores.length} prueba(s) con resultado registrado.`:'Completa tu primer ensayo para activar el diagnostico.'}</p><button class="ghost" onclick="history()">Ver historial completo</button></div></section>
<div class="sectionTitle"><div><h2>Mis pruebas PAES</h2><p>${tests.length} prueba(s) activas en este perfil de estudio.</p></div><button class="ghost" onclick="editProfile()">Cambiar seleccion</button></div><section class="grid">${tests.map(t=>{let l=latest[t.id];return `<article class="card"><h2>${esc(t.title)}</h2><div class="meta"><span class="pill">${t.questions.length} preguntas</span><span class="pill">${t.scoredCount} puntuadas</span><span class="pill">${t.minutes} min</span></div>${l?`<p class="tiny">Ultimo resultado: <b>${l.score} pts</b> · ${l.correct}/${l.scored} correctas</p>`:''}<div class="toolbar compact"><button class="btn" onclick="startTest('${t.id}')">Ensayo base</button><button class="secondary" onclick="startGenerated('${t.id}')">✨ Crear ensayo nuevo</button></div></article>`}).join('')}</section>
<div class="sectionTitle"><div><h2>Generador de nuevos ensayos</h2><p>Crea una version distinta combinando el banco con variantes nuevas controladas y evita repeticiones cuando es posible.</p></div></div><section class="card generatorCallout"><div><h3>✨ Ensayo nuevo en un clic</h3><p>Conserva el numero de preguntas, tiempo y cantidad de items puntuados de la prueba elegida.</p></div><button class="btn" onclick="generatorSetup()">Crear ensayo nuevo</button></section><div class="sectionTitle"><div><h2>Herramientas de estudio</h2></div></div><section class="grid three"><article class="card"><h3>🎯 Practica focalizada</h3><p>Filtra por prueba, eje/habilidad y dificultad.</p><button class="secondary" onclick="practiceSetup()">Configurar practica</button></article><article class="card"><h3>🧠 Diagnostico</h3><p>Fortalezas, prioridades, dominio por contenido y dificultad.</p><button class="secondary" onclick="diagnostic()">Abrir diagnostico</button></article><article class="card"><h3>📈 Historial</h3><p>Compara puntajes y porcentaje de aciertos.</p><button class="secondary" onclick="history()">Ver progreso</button></article></section>`}

function generatorSetup(){resetState();app.innerHTML=`<h1>Crear ensayo nuevo</h1><p>El generador híbrido crea una versión distinta manteniendo la estructura de la prueba seleccionada.</p><section class="card"><div class="setup"><div class="field"><label>Prueba</label><select id="gtest">${visibleTests().map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('')}</select></div><div class="field"><label>Proporción de variantes nuevas</label><select id="gratio"><option value="0.35">35% nuevas</option><option value="0.5" selected>50% nuevas</option><option value="0.65">65% nuevas</option></select></div></div><div class="notice"><b>Cómo funciona:</b> las variantes se generan con plantillas controladas y el resto se selecciona del banco intentando no repetir preguntas ya usadas. No requiere una clave de IA y funciona sin conexión después de cargar la app.</div><div class="toolbar"><button class="btn" onclick="startGenerated($('#gtest').value,+$('#gratio').value)">✨ Generar y comenzar</button><button class="secondary" onclick="home()">Volver</button></div></section><section class="card"><h3>IA futura preparada de forma segura</h3><p class="tiny">Para usar un modelo externo en producción, la clave debe vivir en un backend/función segura, nunca dentro de app.js. Esta V2 final funciona completa sin esa dependencia.</p></section>`}
function startGenerated(id,ratio=0.5){let t=window.PAES_DIVERSITY?PAES_DIVERSITY.buildExam(id,{titleSuffix:'Ensayo nuevo'}):PAES_GENERATOR.createHybridExam(id,ratio);state={test:t,questions:t.questions,answers:{},started:Date.now(),submitted:false,timer:null,mode:'generated'};renderQuiz();state.timer=setInterval(updateTimer,1000);window.scrollTo(0,0)}

function startTest(id){let t=window.PAES_DIVERSITY?PAES_DIVERSITY.buildExam(id,{titleSuffix:'Ensayo PAES'}):PAES_DATA.find(x=>x.id===id);state={test:t,questions:t.questions,answers:{},started:Date.now(),submitted:false,timer:null,mode:'test'};renderQuiz();state.timer=setInterval(updateTimer,1000);window.scrollTo(0,0)}
function updateTimer(){const el=$('#timer');if(!el||!state.started)return;let total=isExamMode(state.mode)?state.test.minutes*60:Math.max(15,state.questions.length*2)*60,left=Math.max(0,total-Math.floor((Date.now()-state.started)/1000));el.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left===0){clearInterval(state.timer);submitCurrent()}}
function reading(){if(!state.test?.readingTexts?.length)return'';return `<details class="passage"><summary><b>Ver todos los textos de lectura</b></summary>${state.test.readingTexts.map(x=>`<h3>Texto ${x.n}: ${esc(x.title)}</h3><p>${esc(x.body)}</p>`).join('')}</details>`}
function readingTextForQuestion(q){
  if(q?.context)return {title:'Texto para esta pregunta',body:q.context};
  if(state.test?.id!=='lectora'||!state.test?.readingTexts?.length)return null;
  const n=Number(q?.n);
  if(!Number.isFinite(n))return null;
  const idx=n<=10?0:n<=20?1:n<=29?2:n<=38?3:n<=47?4:n<=56?5:n<=65?6:null;
  if(idx===null)return null;
  const t=state.test.readingTexts[idx];
  return t?{title:`Texto ${t.n}: ${t.title}`,body:t.body}:null;
}
function inlineReading(q){let t=readingTextForQuestion(q);if(!t)return'';let n=Number(q?.n),starts=new Set([1,11,21,30,39,48,57]);if(state.test?.id==='lectora'&&!starts.has(n)){return `<details class="passage inlinePassage compactPassage"><summary>📖 Ver texto de referencia · ${esc(t.title)}</summary><p>${esc(t.body)}</p></details>`}return `<div class="passage inlinePassage"><b>${esc(t.title)}</b><p>${esc(t.body)}</p></div>`}
function renderQuiz(){let title=isExamMode(state.mode)?state.test.title:`Práctica - ${state.test.title}`;app.innerHTML=`<div class="quiztop"><button class="secondary" onclick="home()">← Salir</button><div class="progress"><div id="bar"></div></div><b id="timer">--:--</b></div><h1>${esc(title)}</h1>${reading()}<div id="questions">${state.questions.map((q,i)=>`<section class="question" id="q${i}"><div class="meta"><span class="pill">Pregunta ${i+1}</span><span class="pill">${esc(q.difficulty||'Referencial')}</span><span class="pill">${esc(q.skill||'General')}</span>${q.source?`<span class="pill source">${esc(q.source)}</span>`:''}${q.scored?'':'<span class="pill">Piloto / no puntuada</span>'}</div>${inlineReading(q)}<h3>${esc(q.text)}</h3>${q.options.map(o=>`<label class="option"><input type="radio" name="q${i}" value="${o.key}" onchange="answer(${i},'${o.key}')"><b>${o.key})</b> ${esc(o.text)}</label>`).join('')}</section>`).join('')}</div><div class="toolbar"><button class="btn" onclick="submitCurrent()">Finalizar y corregir</button><button class="secondary" onclick="window.scrollTo(0,0)">Ir arriba</button></div>`;updateTimer();updateProgress()}
function answer(i,k){state.answers[i]=k;updateProgress()}
function updateProgress(){let b=$('#bar');if(b)b.style.width=(100*Object.keys(state.answers).length/state.questions.length)+'%'}
function scoreEstimate(correct,t){let r=t.scoreRanges.find(x=>correct>=x[0]&&correct<=x[1])||t.scoreRanges[t.scoreRanges.length-1],[a,b,s1,s2,level]=r;return {score:a===b?s2:Math.round(s1+(correct-a)/(b-a)*(s2-s1)),level}}
function breakdown(questions){let skills={},diff={};questions.forEach((q,i)=>{if(!q.scored)return;let ok=state.answers[i]===q.answer;for(const [obj,key] of [[skills,q.skill||'General'],[diff,q.difficulty||'Referencial']]){obj[key]??={ok:0,n:0};obj[key].n++;if(ok)obj[key].ok++}});return {skills,diff}}
function submitCurrent(){if(!state.test||state.submitted)return;let answered=Object.keys(state.answers).length,remaining=state.questions.length-answered;if(remaining>0&&!confirm(`Aún tienes ${remaining} pregunta${remaining===1?'':'s'} sin responder. ¿Quieres finalizar de todas formas?`))return;clearInterval(state.timer);state.submitted=true;let scored=state.questions.filter(q=>q.scored),answeredScored=state.questions.reduce((n,q,i)=>n+(q.scored&&state.answers[i]!=null?1:0),0),correct=state.questions.filter((q,i)=>q.scored&&state.answers[i]===q.answer).length,elapsed=Math.max(1,Math.round((Date.now()-state.started)/60000)),bd=breakdown(state.questions),answeredSkills={};state.questions.forEach((q,i)=>{if(q.scored&&state.answers[i]!=null){let k=q.skill||'General';answeredSkills[k]=(answeredSkills[k]||0)+1}});let est=isExamMode(state.mode)?scoreEstimate(correct,state.test):{score:null,level:answeredScored?practiceLevel(pct(correct,answeredScored)):'Sin actividad'};let wrongItems=state.questions.map((q,i)=>({q,i})).filter(x=>x.q.scored&&state.answers[x.i]!=null&&state.answers[x.i]!==x.q.answer);let wrong=wrongItems.map(x=>x.q.n);let wrongQuestions=wrongItems.map(x=>x.q.source==='Generada'?x.q:null).filter(Boolean);let rec={date:new Date().toISOString(),id:state.test.id,title:state.test.title,mode:state.mode,correct,scored:scored.length,answered,answeredScored,score:est.score,level:est.level,elapsed,skills:bd.skills,difficulty:bd.diff,answeredSkills,wrong,wrongQuestions,generatedCount:state.test.generatedCount||0,bankCount:state.test.bankCount||0};if(answered>0){let h=getHistory();h.unshift(rec);saveHistory(h)}let gameReward=gamifySession(rec);rec.gameRewards=gameReward.rewards;renderResults(rec)}
function practiceLevel(p){return p>=85?'Dominado':p>=65?'En desarrollo':'Prioridad de estudio'}
function renderBars(obj){return Object.entries(obj).sort((a,b)=>pct(b[1].ok,b[1].n)-pct(a[1].ok,a[1].n)).map(([k,v])=>`<div class="barRow"><b>${esc(k)}</b><div class="barTrack"><div class="barFill" style="width:${pct(v.ok,v.n)}%"></div></div><span>${pct(v.ok,v.n)}%</span></div>`).join('')}
function renderResults(r){let p=pct(r.correct,r.scored);app.innerHTML=`<h1>Resultados - ${esc(r.title)}</h1><section class="resultbox"><div class="kpis"><div class="kpi">${isExamMode(r.mode)?'Puntaje estimado':'Rendimiento'}<b class="score">${isExamMode(r.mode)?r.score:p+'%'}</b>${esc(r.level)}</div><div class="kpi">Correctas<b>${r.correct}/${r.scored}</b>${p}%</div><div class="kpi">Respondidas<b>${Object.keys(state.answers).length}/${state.questions.length}</b></div><div class="kpi">Tiempo usado<b>${r.elapsed} min</b></div></div>${r.mode==='generated'?`<p class="tiny"><b>Ensayo híbrido:</b> ${r.generatedCount} variantes generadas + ${r.bankCount} preguntas del banco.</p>`:''}<p class="tiny">Puntajes y niveles son aproximaciones de estudio; no reemplazan la escala oficial de cada aplicación PAES.</p></section>${r.gameRewards?.length?`<section class="rewardToast card"><h2>🎉 Recompensas de esta sesión</h2>${r.gameRewards.map(x=>`<div>${esc(x)}</div>`).join('')}<button class="ghost" onclick="gamification()">Ver mi racha y premios</button></section>`:(r.answered===0?`<section class="card"><h2>Sin recompensas</h2><p>No respondiste preguntas en esta sesión, por eso no suma XP, misión, racha ni progreso.</p></section>`:'')}<div class="sectionTitle"><div><h2>Desempeño por eje/habilidad</h2></div></div><section class="card">${renderBars(r.skills)}</section><div class="sectionTitle"><div><h2>Por dificultad</h2></div></div><section class="card">${renderBars(r.difficulty)}</section><div class="toolbar"><button class="btn" onclick="review()">Revisar respuestas</button><button class="secondary" onclick="diagnostic()">Ver diagnóstico acumulado</button><button class="ghost" onclick="home()">Inicio</button></div>`;window.scrollTo(0,0)}
function review(){let t=state.test;app.innerHTML=`<h1>Revisión - ${esc(t.title)}</h1><div class="toolbar"><button class="secondary" onclick="home()">Inicio</button><button class="ghost" onclick="practiceWrong('${t.id}')">Practicar errores</button></div>${state.questions.map((q,i)=>{let mine=state.answers[i],ok=mine===q.answer;return `<section class="question"><div class="meta"><span class="pill">Pregunta ${i+1}</span><span class="pill">${esc(q.difficulty||'')}</span><span class="pill">${esc(q.skill||'')}</span>${q.source?`<span class="pill source">${esc(q.source)}</span>`:''}</div>${inlineReading(q)}<h3>${esc(q.text)}</h3>${q.options.map(o=>`<div class="option ${o.key===q.answer?'correct':(o.key===mine&&!ok?'wrong':'')}"><b>${o.key})</b> ${esc(o.text)}</div>`).join('')}<div class="explain"><b>${ok?'Correcta':'Tu respuesta: '+(mine||'Sin responder')+' · Correcta: '+q.answer}</b><br>${esc(q.explanation)}</div></section>`}).join('')}`;window.scrollTo(0,0)}
function allSkillsFor(id){let t=PAES_DATA.find(x=>x.id===id);return [...new Set(t.questions.map(q=>q.skill||'General'))].sort()}
function practiceSetup(){resetState();app.innerHTML=`<h1>Práctica focalizada</h1><p>Configura una sesión corta para reforzar exactamente lo que necesitas.</p><section class="card"><div class="setup"><div class="field"><label>Prueba</label><select id="ptest" onchange="refreshSkillOptions()">${visibleTests().map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('')}</select></div><div class="field"><label>Eje / habilidad</label><select id="pskill"></select></div><div class="field"><label>Dificultad</label><select id="pdiff"><option value="all">Todas</option><option>Fácil</option><option>Media</option><option>Difícil</option></select></div><div class="field"><label>Cantidad</label><select id="pcount"><option>5</option><option selected>10</option><option>15</option><option>20</option></select></div></div><div class="toolbar"><button class="btn" onclick="startPractice()">Comenzar práctica</button><button class="secondary" onclick="home()">Volver</button></div></section><div class="sectionTitle"><div><h2>Atajos</h2></div></div><section class="grid">${visibleTests().map(t=>`<article class="card"><h3>${esc(t.title)}</h3><p>Repite preguntas que hayas fallado previamente.</p><button class="ghost" onclick="practiceWrong('${t.id}')">Practicar mis errores</button></article>`).join('')}</section>`;refreshSkillOptions()}
function refreshSkillOptions(){let id=$('#ptest')?.value||visibleTests()[0]?.id||PAES_DATA[0].id,el=$('#pskill');if(el)el.innerHTML='<option value="all">Todos</option>'+allSkillsFor(id).map(s=>`<option>${esc(s)}</option>`).join('')}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
function startPractice(){let id=$('#ptest').value,skill=$('#pskill').value,diff=$('#pdiff').value,count=+$(`#pcount`).value,t=PAES_DATA.find(x=>x.id===id),qs=window.PAES_DIVERSITY?PAES_DIVERSITY.trainingPool(id,skill,diff,Math.max(count,40)):t.questions.filter(q=>(skill==='all'||q.skill===skill)&&(diff==='all'||q.difficulty===diff));if(!qs.length){alert('No hay preguntas con esa combinación. Prueba otro filtro.');return}qs=shuffled(qs).slice(0,count);state={test:t,questions:qs,answers:{},started:Date.now(),submitted:false,timer:null,mode:'practice'};renderQuiz();state.timer=setInterval(updateTimer,1000);window.scrollTo(0,0)}
function practiceWrong(id){let h=getHistory().filter(x=>x.id===id&&((x.wrong?.length)||(x.wrongQuestions?.length))),nums=[...new Set(h.flatMap(x=>x.wrong||[]).map(String))],t=PAES_DATA.find(x=>x.id===id),bank=t.questions.filter(q=>nums.includes(String(q.n))),generated=h.flatMap(x=>x.wrongQuestions||[]),seen=new Set(),genUnique=generated.filter(q=>{let k=q.id||q.text;if(seen.has(k))return false;seen.add(k);return true}),qs=[...bank,...genUnique];if(!qs.length){alert('Aún no tienes errores registrados en esta prueba. Completa un ensayo o práctica primero.');return}state={test:t,questions:shuffled(qs).slice(0,20),answers:{},started:Date.now(),submitted:false,timer:null,mode:'errors'};renderQuiz();state.timer=setInterval(updateTimer,1000);window.scrollTo(0,0)}
function history(){resetState();let h=getHistory();app.innerHTML=`<h1>Historial</h1><div class="card">${h.length?h.map(x=>`<div class="historyrow"><div><b>${esc(x.title)}</b><br><small>${new Date(x.date).toLocaleString('es-CL')} · ${isExamMode(x.mode)?(x.mode==='generated'?'Ensayo generado':'Ensayo base'):'Práctica'}</small></div><b>${isExamMode(x.mode)?x.score+' pts':pct(x.correct,x.scored)+'%'}</b><span>${x.correct}/${x.scored} · ${esc(x.level)}</span></div>`).join(''):'<div class="empty">Aún no hay sesiones finalizadas.</div>'}</div><div class="toolbar"><button class="secondary" onclick="home()">Volver</button>${h.length?'<button class="danger" onclick="clearHistory()">Borrar historial</button>':''}</div>`}
function clearHistory(){if(confirm('¿Seguro que quieres borrar todo el historial y diagnóstico?')){localStorage.removeItem(scopedKey('paesHistoryV2'));history()}}
function diagnostic(){resetState();let h=getHistory();if(!h.length){app.innerHTML=`<h1>Diagnóstico</h1><section class="card empty"><h2>Aún no hay datos suficientes</h2><p>Completa al menos un ensayo o práctica para activar fortalezas, prioridades y recomendaciones.</p><button class="btn" onclick="home()">Elegir ensayo</button></section>`;return}
let tests=h.filter(x=>isExamMode(x.mode)),sessions=h,skills={},diff={};sessions.forEach(r=>{Object.entries(r.skills||{}).forEach(([k,v])=>{skills[k]??={ok:0,n:0};skills[k].ok+=v.ok;skills[k].n+=v.n});Object.entries(r.difficulty||{}).forEach(([k,v])=>{diff[k]??={ok:0,n:0};diff[k].ok+=v.ok;diff[k].n+=v.n})});let ordered=Object.entries(skills).sort((a,b)=>pct(a[1].ok,a[1].n)-pct(b[1].ok,b[1].n)),priority=ordered.slice(0,3),strength=[...ordered].reverse().slice(0,3),avg=tests.length?Math.round(tests.reduce((a,b)=>a+b.score,0)/tests.length):null,trend=tests.slice(0,10).reverse();let recs=priority.map(([k,v])=>{let p=pct(v.ok,v.n),qty=p<50?20:p<65?15:10;return `<div class="recommend"><strong>${p<60?'🔴':'🟡'} ${esc(k)} · ${p}%</strong>Realiza ${qty} preguntas focalizadas de este eje, revisa cada error y repite el bloque hasta superar 70%.</div>`}).join('');
app.innerHTML=`<h1>Diagnóstico acumulado</h1><section class="resultbox"><div class="kpis"><div class="kpi">Promedio ensayos<b>${avg??'--'}${avg?' pts':''}</b></div><div class="kpi">Sesiones registradas<b>${sessions.length}</b></div><div class="kpi">Mejor fortaleza<b>${strength[0]?esc(strength[0][0]):'--'}</b>${strength[0]?pct(strength[0][1].ok,strength[0][1].n)+'%':''}</div><div class="kpi">Prioridad principal<b>${priority[0]?esc(priority[0][0]):'--'}</b>${priority[0]?pct(priority[0][1].ok,priority[0][1].n)+'%':''}</div></div></section>
<div class="sectionTitle"><div><h2>Semáforo de dominio</h2><p>🟢 80%+ · 🟡 60-79% · 🔴 menos de 60%</p></div></div><section class="mastery">${ordered.map(([k,v])=>{let p=pct(v.ok,v.n),c=p>=80?'g':p>=60?'y':'r';return `<div class="${c}"><b>${p>=80?'🟢':p>=60?'🟡':'🔴'} ${esc(k)}</b><div class="score" style="font-size:28px">${p}%</div><span class="tiny">${v.ok}/${v.n} correctas acumuladas</span></div>`}).join('')}</section>
<section class="card" style="border-left:5px solid #7c3aed"><div class="eyebrow">CLASE PERSONALIZADA</div><h2>🎓 Refuerza tu área más baja</h2><p>PAES Trainer toma tu diagnóstico acumulado y prepara una clase de refuerzo tipo preuniversitario, con explicación, estrategia, 10 preguntas y corrección detallada.</p><button class="btn" onclick="personalizedClasses()">Crear mi clase personalizada</button></section>
<div class="sectionTitle"><div><h2>Plan recomendado</h2><p>Prioridades calculadas según tus resultados acumulados.</p></div></div>${recs||'<section class="card">Sin prioridades detectadas.</section>'}
<div class="sectionTitle"><div><h2>Rendimiento por dificultad</h2></div></div><section class="card">${renderBars(diff)}</section>
<div class="sectionTitle"><div><h2>Evolución de ensayos</h2><p>${trend.length?'Últimos '+trend.length+' ensayos completos':'Completa ensayos completos para ver puntajes.'}</p></div></div><section class="card">${trend.length?`<div class="trend">${trend.map(x=>`<i style="height:${Math.max(8,(x.score-100)/9)}%" title="${x.score} pts"></i>`).join('')}</div><div class="tiny" style="margin-top:8px">${trend.map(x=>x.score).join(' → ')} pts</div>`:'<div class="empty">Sin ensayos completos registrados.</div>'}</section>
<div class="sectionTitle"><div><h2>Fortalezas actuales</h2></div></div><section class="grid three">${strength.map(([k,v])=>`<article class="card"><h3>🟢 ${esc(k)}</h3><div class="score" style="font-size:34px">${pct(v.ok,v.n)}%</div><p class="tiny">Mantén el dominio incorporando preguntas difíciles.</p></article>`).join('')}</section><div class="toolbar"><button class="btn" onclick="practiceSetup()">Entrenar una prioridad</button><button class="secondary" onclick="home()">Inicio</button></div>`;window.scrollTo(0,0)}

// ===== CAPA COMERCIAL / LICENCIAS =====
const CFG=window.PAES_CONFIG||{};
let sb=null, currentAccess=null, commercialMode='public';
const isConfigured=()=>CFG.SUPABASE_URL&&CFG.SUPABASE_PUBLISHABLE_KEY&&!String(CFG.SUPABASE_URL).includes('PEGA_AQUI')&&!String(CFG.SUPABASE_PUBLISHABLE_KEY).includes('PEGA_AQUI');
const whatsappUrl=()=>`https://wa.me/${CFG.WHATSAPP_NUMBER||'56995132714'}?text=${encodeURIComponent('Hola, quiero comprar el acceso completo por 1 año a PAES Trainer por $15.990. Vengo desde la demo.')}`;
function setNav(show){let n=$('#topnav');if(n)n.style.display=show?'flex':'none'}
const TRIAL_KEY='paesFullTrialV1';
let trialTimer=null;
function trialData(){try{return JSON.parse(localStorage.getItem(TRIAL_KEY)||'null')}catch{return null}}
function trialState(){let t=trialData();if(!t)return 'none';return Date.now()<Number(t.endsAt||0)?'active':'expired'}
function trialRemainingMs(){let t=trialData();return t?Math.max(0,Number(t.endsAt||0)-Date.now()):0}
function trialRemainingText(){let ms=trialRemainingMs(),h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000);return `${h} h ${m} min`}
function ensureTrialProfile(){let id='trial_full',profiles=getProfiles(),p=profiles.find(x=>x.id===id);if(!p){p={id,name:'Mi prueba FULL',goal:750,studyProfile:'completas',tests:[],guest:false,trial:true,created:new Date().toISOString()};profiles.push(p);saveProfiles(profiles)}setActiveId(id);return p}
function scheduleTrialExpiry(){clearTimeout(trialTimer);let left=trialRemainingMs();if(left>0)trialTimer=setTimeout(()=>trialExpiredScreen(),Math.min(left,2147483647))}
function startFullTrial(){let status=trialState();if(status==='expired'){trialExpiredScreen();return}if(status==='none'){let startedAt=Date.now();localStorage.setItem(TRIAL_KEY,JSON.stringify({startedAt,endsAt:startedAt+24*60*60*1000}))}commercialMode='trial';currentAccess=null;ensureTrialProfile();setNav(true);scheduleTrialExpiry();home()}
function commercialHome(){if(commercialMode==='member')return home();if(commercialMode==='trial'&&trialState()==='active')return home();return landing()}
function trialExpiredScreen(){clearTimeout(trialTimer);commercialMode='public';currentAccess=null;setNav(false);app.innerHTML=`<section class="loginWrap"><div class="card loginCard"><div class="expiredIcon">⏰</div><div class="eyebrow">PRUEBA FULL FINALIZADA</div><h1>Tu día de prueba terminó</h1><p>Durante 24 horas pudiste usar PAES Trainer con acceso completo. Para seguir estudiando, activa tu acceso por 1 año.</p><div class="licenseBox"><span>Acceso completo</span><b>$15.990</b><small>1 año · Todas las funciones</small></div><a class="waBtn" href="${whatsappUrl()}" target="_blank" rel="noopener">Comprar acceso por $15.990</a><button class="secondary full" onclick="loginScreen()">Ya tengo usuario</button><button class="ghost full" onclick="landing()">Volver</button></div></section>`;window.scrollTo(0,0)}
function trialAccount(){if(trialState()!=='active'){trialExpiredScreen();return}let p=getActiveProfile()||ensureTrialProfile(),g=getGame(),h=getHistory();app.innerHTML=`<h1>Mi prueba FULL</h1><section class="grid"><article class="card"><div class="eyebrow">1 DÍA DE PRUEBA FULL</div><h2>${esc(p.name)}</h2><div class="licenseBox"><span>Tiempo restante</span><b>${trialRemainingText()}</b><small>Al finalizar, la prueba se bloqueará automáticamente.</small></div><div class="meta"><span class="pill">🔥 ${g.streak} días</span><span class="pill">⭐ ${g.xp} XP</span><span class="pill">${h.length} sesiones</span></div><button class="secondary" onclick="editProfile()">Editar perfil de estudio</button></article><article class="card"><h3>Todo está desbloqueado</h3><p>Durante estas 24 horas puedes usar ensayos, generador, diagnóstico, historial, práctica de errores, rachas, XP y todas las pruebas PAES.</p><a class="waBtn" href="${whatsappUrl()}" target="_blank" rel="noopener">Comprar 1 año · $15.990</a></article></section><div class="toolbar"><button class="btn" onclick="home()">Volver al inicio</button></div>`;setTimeout(()=>window.PAES_RATINGS?.mountMember?.(),0)}
function landing(){
  resetState();commercialMode='public';currentAccess=null;setNav(false);
  let trialButton=`<button class="btn bigBtn landingPrimary" onclick="trialSignupScreen()">🚀 Crear mi prueba FULL de 1 día</button>`;
  app.innerHTML=`
<section class="landingV34">
  <div class="landingHeroV34">
    <div class="landingCopyV34">
      <div class="landingBadgeV34">🎓 PREPARACIÓN PAES PERSONALIZADA</div>
      <h1>Tu PAES. Tu ritmo.<br><span>Tu progreso. 🚀</span></h1>
      <p class="landingLeadV34">Practica con foco, descubre qué necesitas reforzar y avanza paso a paso con una ruta pensada para ti.</p>
      <div class="landingBenefitsV34">
        <div><span>🎯</span><b>Entrenamiento personalizado</b><small>Estudia justo lo que más necesitas mejorar.</small></div>
        <div><span>📈</span><b>Mira cómo avanzas</b><small>Diagnóstico, puntajes y progreso en un solo lugar.</small></div>
        <div><span>🔥</span><b>Mantén tu racha</b><small>XP, desafíos y logros que hacen más entretenido estudiar.</small></div>
        <div><span>🧠</span><b>Aprende de verdad</b><small>Clases, cápsulas, ensayos y material DEMRE.</small></div>
      </div>
      <div class="landingActionsV34">${trialButton}<button class="secondary bigBtn landingSecondary" onclick="loginScreen()">🔑 Ya tengo cuenta</button></div>
      <p class="landingTrialV34"><b>24 horas FULL</b> · Sin tarjeta · Activas la prueba cuando tú quieras.</p>
    </div>
    <aside class="landingOfferV34">
      <div class="landingOfferTopV34"><span>✨ ACCESO COMPLETO</span><b>1 año</b></div>
      <div class="landingPriceV34"><strong>$15.990</strong><small>pago único</small></div>
      <p>Todo PAES Trainer desbloqueado durante 365 días.</p>
      <div class="landingFeatureV34"><span>✓</span> Todas las pruebas PAES</div>
      <div class="landingFeatureV34"><span>✓</span> Entrenamiento adaptativo</div>
      <div class="landingFeatureV34"><span>✓</span> Ensayos y prácticas ilimitadas</div>
      <div class="landingFeatureV34"><span>✓</span> Clases, cápsulas y diagnóstico</div>
      <div class="landingFeatureV34"><span>✓</span> Progreso, rachas y recompensas</div>
      <div class="landingFeatureV34"><span>✓</span> Biblioteca de material DEMRE</div>
      <a class="waBtn landingWhatsAppV34" href="${whatsappUrl()}" target="_blank" rel="noopener">💬 Comprar por WhatsApp</a>
      <small class="landingSafeV34">Tú realizas la transferencia directamente con el administrador.</small>
    </aside>
  </div>
  <div class="landingSocialV34">
    <div><span>🆓</span><b>Prueba primero</b><small>Conoce toda la plataforma antes de comprar.</small></div>
    <div><span>📚</span><b>Enfoque PAES</b><small>Contenido organizado con referencia en temarios DEMRE.</small></div>
    <div><span>⚡</span><b>Sin perder tiempo</b><small>La app prioriza tus debilidades y tu progreso.</small></div>
  </div>
  <div id="ratingPublicMount"></div>
</section>`;
  setTimeout(()=>window.PAES_RATINGS?.mountPublic?.(),0);
  window.scrollTo(0,0)
}
function trialSignupScreen(message=''){commercialMode='public';setNav(false);app.innerHTML=`<section class="loginWrap"><div class="card loginCard"><div class="eyebrow">1 DÍA FULL · CUENTA PERSONAL</div><h1>Crea tu usuario de prueba</h1><p>Elige un usuario y una contraseña. Tendrás 24 horas FULL. Si después compras el acceso anual, <b>conservas exactamente este mismo usuario</b>: el administrador solo activa tu año.</p>${message?`<div class="loginMessage">${esc(message)}</div>`:''}<div class="field"><label>Tu nombre</label><input id="trialName" autocomplete="name" placeholder="Ej.: Sofía"></div><div class="field"><label>Usuario</label><input id="trialUser" autocomplete="username" placeholder="Ej.: sofia.paes"></div><div class="field"><label>Contraseña</label><input id="trialPass" type="password" autocomplete="new-password" placeholder="Mínimo 8 caracteres"></div><div class="field"><label>Repite tu contraseña</label><input id="trialPass2" type="password" autocomplete="new-password" placeholder="Repite la contraseña" onkeydown="if(event.key==='Enter')createTrialAccount()"></div><button class="btn full" onclick="createTrialAccount()">Activar mis 24 horas FULL</button><p class="tiny">Guarda tu usuario y contraseña. Los necesitarás para volver a entrar desde celular o computador.</p><div class="loginLinks"><button class="ghost" onclick="landing()">Volver</button><button class="ghost" onclick="loginScreen()">Ya creé mi usuario</button></div></div></section>`;window.scrollTo(0,0)}
async function createTrialAccount(){let client=await initSupabase();if(!client){trialSignupScreen('Primero debes conectar Supabase.');return}let display_name=($('#trialName')?.value||'').trim(),username=($('#trialUser')?.value||'').trim().toLowerCase().replace(/[^a-z0-9._-]/g,''),password=$('#trialPass')?.value||'',password2=$('#trialPass2')?.value||'';if(!display_name){trialSignupScreen('Escribe tu nombre.');return}if(!/^[a-z0-9._-]{3,40}$/.test(username)){trialSignupScreen('El usuario debe tener entre 3 y 40 caracteres y usar solo letras, números, punto, guion o guion bajo.');return}if(password.length<8){trialSignupScreen('La contraseña debe tener al menos 8 caracteres.');return}if(password!==password2){trialSignupScreen('Las contraseñas no coinciden.');return}let email=`${username}@paestrainer.app`;let {data,error}=await client.auth.signUp({email,password,options:{data:{trial:true,display_name,username}}});if(error){trialSignupScreen(error.message?.toLowerCase().includes('already')?'Ese usuario ya existe. Elige otro o entra con tu cuenta.':'No pudimos crear la prueba: '+error.message);return}if(!data?.session){trialSignupScreen('La cuenta se creó, pero Supabase está pidiendo confirmar correo. En Supabase debes desactivar Confirm email para permitir la prueba automática.');return}await new Promise(r=>setTimeout(r,350));await enterMember(data.session)}
function loginScreen(message=''){commercialMode='public';setNav(false);app.innerHTML=`<section class="loginWrap"><div class="card loginCard"><div class="eyebrow">ACCESO CLIENTES</div><h1>Iniciar sesión</h1><p>Usa el usuario y contraseña que te entregó el administrador.</p>${message?`<div class="loginMessage">${esc(message)}</div>`:''}<div class="field"><label>Usuario</label><input id="loginUser" autocomplete="username" placeholder="Ej.: catalina2027"></div><div class="field"><label>Contraseña</label><input id="loginPass" type="password" autocomplete="current-password" placeholder="Tu contraseña" onkeydown="if(event.key==='Enter')login()"></div><button class="btn full" onclick="login()">Entrar</button><div class="loginLinks"><button class="ghost" onclick="landing()">Volver</button><a href="${whatsappUrl()}" target="_blank" rel="noopener">Comprar acceso</a></div>${!isConfigured()?'<div class="setupWarning"><b>Modo de configuración:</b> aún falta conectar Supabase en <code>config.js</code>. La demo funciona igualmente.</div>':''}</div></section>`}
async function initSupabase(){if(!isConfigured()||!window.supabase)return null;if(!sb)sb=window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
function deviceId(){let k='paesDeviceIdV1',v=localStorage.getItem(k);if(!v){v='d_'+(crypto.randomUUID?crypto.randomUUID():uid());localStorage.setItem(k,v)}return v}
async function login(){let client=await initSupabase();if(!client){loginScreen('Primero debes conectar Supabase. Sigue el README incluido en el ZIP.');return}let username=($('#loginUser')?.value||'').trim().toLowerCase().replace(/[^a-z0-9._-]/g,''),password=$('#loginPass')?.value||'';if(!username||!password){loginScreen('Escribe tu usuario y contraseña.');return}let {data,error}=await client.auth.signInWithPassword({email:`${username}@paestrainer.app`,password});if(error){loginScreen('Usuario o contraseña incorrectos.');return}await enterMember(data.session)}
async function fetchAccess(userId){let client=await initSupabase();let {data,error}=await client.from('user_access').select('*').eq('user_id',userId).single();if(error)return null;return data}
async function claimDevice(){let client=await initSupabase();let {data,error}=await client.rpc('claim_device',{p_device_id:deviceId()});if(error)return {ok:false,message:'No fue posible validar este dispositivo.'};return data}
async function enterMember(session){if(!session?.user){landing();return}let access=await fetchAccess(session.user.id);if(!access){await sb.auth.signOut();loginScreen('Esta cuenta no tiene una licencia asignada. Escríbenos por WhatsApp.');return}let now=Date.now(),expiry=new Date(access.access_until).getTime();if(!access.active||!expiry||expiry<=now){currentAccess=access;expiredScreen(access);return}currentAccess=access;commercialMode='member';ensureMemberProfile(access);setNav(true);syncGamification(getGame()).catch(()=>{});home()}
function ensureMemberProfile(access){let id=`member_${access.user_id}`,profiles=getProfiles(),p=profiles.find(x=>x.id===id);if(!p){p={id,name:access.display_name||access.username||'Estudiante',goal:750,studyProfile:'completas',tests:[],guest:false,member:true,created:new Date().toISOString()};profiles.push(p);saveProfiles(profiles)}else if(access.display_name&&p.name!==access.display_name){p.name=access.display_name;saveProfiles(profiles)}setActiveId(id)}
function expiredScreen(access){commercialMode='public';setNav(false);app.innerHTML=`<section class="loginWrap"><div class="card loginCard"><div class="expiredIcon">⌛</div><h1>${access?.access_type==='trial'?'Tu prueba FULL terminó':'Tu acceso ha vencido'}</h1><p>${access?.access_type==='trial'?'Tus 24 horas finalizaron. Tu usuario @'+esc(access.username)+' queda reservado para que, si compras, el administrador active el año completo sin cambiar tus credenciales.':'Tu licencia terminó el <b>'+new Date(access.access_until).toLocaleDateString('es-CL')+'</b>. Tu progreso local no se elimina.'}</p><a class="waBtn" href="${whatsappUrl()}" target="_blank" rel="noopener">${access?.access_type==='trial'?'Comprar y activar este usuario':'Renovar por 1 año'}</a><button class="ghost full" onclick="logout()">Cerrar sesión</button></div></section>`}
function deviceBlockedScreen(){commercialMode='public';setNav(false);app.innerHTML=`<section class="loginWrap"><div class="card loginCard"><div class="expiredIcon">🔐</div><h1>Revisa tu acceso</h1><p>Tu cuenta puede usarse en celular y computador. Si no puedes entrar, revisa usuario, contraseña y vigencia de la licencia.</p><a class="waBtn" href="${whatsappUrl()}" target="_blank" rel="noopener">Pedir ayuda por WhatsApp</a><button class="ghost full" onclick="landing()">Volver</button></div></section>`}
async function logout(){if(sb)await sb.auth.signOut();currentAccess=null;commercialMode='public';setActiveId('');landing()}
function daysLeft(){if(!currentAccess?.access_until)return 0;return Math.max(0,Math.ceil((new Date(currentAccess.access_until)-Date.now())/86400000))}
function account(){if(commercialMode==='trial'){trialAccount();return}let p=getActiveProfile();if(commercialMode!=='member'||!p){landing();return}let h=getHistory(),isAdmin=currentAccess?.role==='admin';app.innerHTML=`<h1>Mi cuenta</h1><section class="grid"><article class="card"><div class="profileSummary"><span class="avatar big">${esc((p.name||'P')[0].toUpperCase())}</span><div><h2>${esc(p.name)}</h2><p>@${esc(currentAccess?.username||'usuario')} · ${gradeLabel(p)} · ${esc(studyLabel(p))}</p></div></div><div class="licenseBox"><span>${currentAccess?.access_type==='trial'?'Prueba FULL activa':'Licencia activa'}</span><b>${currentAccess?.access_type==='trial'?Math.max(0,Math.ceil((new Date(currentAccess.access_until)-Date.now())/3600000))+' horas restantes':daysLeft()+' días restantes'}</b><small>${currentAccess?.access_type==='trial'?'Si compras, conservarás este mismo usuario.':'Vence: '+new Date(currentAccess.access_until).toLocaleDateString('es-CL')}</small></div>${(()=>{let g=getGame();return `<div class="meta"><span class="pill">🔥 ${g.streak} días</span><span class="pill">⭐ ${g.xp} XP</span><span class="pill">🏅 ${g.badges.length} medallas</span></div>`})()}<button class="secondary" onclick="gamification()">Ver racha y premios</button><button class="ghost" onclick="editProfile()">Editar perfil de estudio</button></article><article class="card"><h3>Privacidad y acceso</h3><p>Puedes iniciar sesión con tu cuenta en celular y computador. Cada navegador mantiene su progreso local; tu licencia sigue protegida por usuario, contraseña y fecha de vigencia.</p><div class="meta"><span class="pill">${h.length} sesiones guardadas aquí</span><span class="pill">📱💻 Multidispositivo</span></div><div class="toolbar"><button class="danger" onclick="clearMyData()">Borrar mi progreso local</button><button class="ghost" onclick="logout()">Cerrar sesión</button></div></article></section>${isAdmin?`<section class="adminCallout card"><div><div class="eyebrow">ADMINISTRADOR</div><h2>Gestión de clientes</h2><p>Crea accesos de 1 año, renueva, bloquea y cambia contraseñas.</p></div><button class="btn" onclick="adminPanel()">Abrir panel administrador</button></section>`:''}<div id="ratingMemberMount"></div><div class="toolbar"><button class="btn" onclick="home()">Volver al inicio</button></div>`;setTimeout(()=>window.PAES_RATINGS?.mountMember?.(),0)}
async function adminInvoke(body){let client=await initSupabase();let {data:ses}=await client.auth.getSession();let token=ses?.session?.access_token;if(!token)throw new Error('Sesión no válida');let res=await fetch(`${CFG.SUPABASE_URL}/functions/v1/admin-users`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`,'apikey':CFG.SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify(body)});let data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Error del administrador');return data}
async function adminPanel(){if(currentAccess?.role!=='admin'){account();return}setNav(true);app.innerHTML=`<h1>Panel administrador</h1><section class="card"><div class="sectionTitle"><div><h2>Crear cliente · 1 año</h2><p>El usuario queda activo por 365 días y puede usar su cuenta en celular y computador.</p></div></div><div class="setup"><div class="field"><label>Nombre del alumno</label><input id="aname" placeholder="Ej.: Camila Pérez"></div><div class="field"><label>Usuario</label><input id="auser" placeholder="Ej.: camila2027"></div><div class="field"><label>Contraseña inicial</label><input id="apass" type="text" placeholder="Mínimo 8 caracteres"></div></div><div class="toolbar"><button class="btn" onclick="adminCreate()">Crear acceso por 1 año</button><button class="secondary" onclick="loadAdminUsers()">Actualizar lista</button><button class="ghost" onclick="account()">Volver</button></div><div id="adminNotice"></div></section><section class="sectionTitle"><div><h2>Clientes</h2></div></section><div id="adminUsers" class="card"><div class="empty">Cargando...</div></div><div id="adminRatings"></div>`;await loadAdminUsers();setTimeout(()=>window.PAES_RATINGS?.mountAdmin?.(),0)}
function adminNotice(msg,bad=false){let e=$('#adminNotice');if(e)e.innerHTML=`<div class="${bad?'adminError':'adminSuccess'}">${esc(msg)}</div>`}
async function adminCreate(){let display_name=$('#aname')?.value.trim(),username=$('#auser')?.value.trim().toLowerCase(),password=$('#apass')?.value||'';if(!display_name||!username||password.length<8){adminNotice('Completa nombre, usuario y una contraseña de al menos 8 caracteres.',true);return}try{await adminInvoke({action:'create_user',display_name,username,password});adminNotice(`Usuario ${username} creado con 365 días de acceso.`);$('#aname').value='';$('#auser').value='';$('#apass').value='';await loadAdminUsers()}catch(e){adminNotice(e.message,true)}}
async function loadAdminUsers(){let box=$('#adminUsers');try{let data=await adminInvoke({action:'list_users'}),users=data.users||[];box.innerHTML=users.length?users.map(u=>`<div class="adminUser"><div><b>${esc(u.display_name||u.username)}</b><small>@${esc(u.username)} · ${u.role==='admin'?'Administrador':(u.access_type==='trial'?'Prueba 24 h':'Cliente anual')}</small></div><div><span class="status ${u.active&&new Date(u.access_until)>new Date()?'good':'bad'}">${u.active?'Activo':'Bloqueado'}</span><small>Vence ${new Date(u.access_until).toLocaleDateString('es-CL')}</small>${u.game?`<small>🔥 ${u.game.streak||0} días · ⭐ ${u.game.xp||0} XP · Última actividad ${u.game.last_active_date?new Date(u.game.last_active_date+'T12:00:00').toLocaleDateString('es-CL'):'sin actividad'}</small>`:''}</div><div class="adminActions">${u.role!=='admin'?`<button class="ghost" onclick="adminAction('renew_user','${u.user_id}')">${u.access_type==='trial'?'Activar 1 año':'+1 año'}</button><button class="ghost" onclick="adminPassword('${u.user_id}')">Nueva clave</button><button class="${u.active?'danger':'secondary'}" onclick="adminAction('toggle_user','${u.user_id}',${!u.active})">${u.active?'Bloquear':'Activar'}</button><button class="danger" onclick="adminDelete('${u.user_id}','${esc(u.username)}')">Eliminar</button>`:''}</div></div>`).join(''):'<div class="empty">No hay clientes todavía.</div>'}catch(e){box.innerHTML=`<div class="adminError">${esc(e.message)}</div>`}}
async function adminAction(action,user_id,active){try{await adminInvoke({action,user_id,active});await loadAdminUsers()}catch(e){alert(e.message)}}
async function adminPassword(user_id){let password=prompt('Escribe la nueva contraseña (mínimo 8 caracteres):');if(!password)return;if(password.length<8){alert('Debe tener al menos 8 caracteres.');return}try{await adminInvoke({action:'reset_password',user_id,password});alert('Contraseña actualizada.')}catch(e){alert(e.message)}}
async function adminDelete(user_id,username){if(!confirm(`¿Eliminar definitivamente al usuario @${username}?\n\nSe borrarán su acceso, racha, XP y cuenta de inicio de sesión. Esta acción no se puede deshacer.`))return;let check=prompt(`Para confirmar, escribe ELIMINAR`);if(check!=='ELIMINAR'){alert('Eliminación cancelada.');return}try{await adminInvoke({action:'delete_user',user_id});alert(`Usuario @${username} eliminado.`);await loadAdminUsers()}catch(e){alert(e.message)}}
async function bootCommercial(){migrateLegacy();await initSupabase();if(sb){let {data}=await sb.auth.getSession();if(data?.session){await enterMember(data.session);return}}landing()}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});bootCommercial();
