// PAES Trainer - Aprende PAES
// Ruta pedagogica 3ro/4to medio. Contenidos alineados a ejes/habilidades DEMRE vigentes.
const LEARN_KEY='paesLearningV1';
const DEMRE_REVIEW='Agosto 2026 · Proceso de Admisión 2027';
const DEMRE_URL='https://portaldemre.demre.cl/paes/factores-seleccion/pruebas-acceso-paes';

const PAES_SYLLABUS={
  lectura:{name:'Competencia Lectora',icon:'📚',skills:['Localizar información explícita','Interpretar relaciones, ideas y sentidos','Evaluar contenido, forma, propósito y recursos del texto'],focus3:['Lectura activa y rastreo de evidencia','Idea principal, inferencias y relaciones','Vocabulario y sentido por contexto','Diferenciar hecho, opinión y propósito'],focus4:['Integración de información en textos extensos','Evaluación de argumentos y fuentes','Relación entre textos y perspectivas','Administración del tiempo y descarte de distractores']},
  m1:{name:'Competencia Matemática 1 (M1)',icon:'🧮',skills:['Resolver problemas','Modelar','Representar','Argumentar'],focus3:['Números y proporcionalidad','Álgebra, ecuaciones y funciones','Geometría y medición','Probabilidad y estadística'],focus4:['Problemas multietapa','Modelación con funciones','Lectura de gráficos y tablas','Integración de ejes y estrategias PAES']},
  m2:{name:'Competencia Matemática 2 (M2)',icon:'📐',skills:['Resolver problemas','Modelar','Representar','Argumentar'],focus3:['Profundización algebraica','Funciones y cambio','Geometría analítica y relaciones','Probabilidad y análisis de datos'],focus4:['Modelos matemáticos más complejos','Análisis de condiciones y suficiencia de datos','Argumentación y validación','Integración de contenidos de 7° básico a 4° medio']},
  historia:{name:'Historia y Ciencias Sociales',icon:'🏛️',skills:['Pensamiento temporal y espacial','Análisis de fuentes','Pensamiento crítico','Comprensión de procesos históricos y sociales'],focus3:['Procesos históricos de Chile y el mundo','Cambios políticos, sociales y económicos','Ciudadanía, instituciones y democracia','Lectura de fuentes, mapas y gráficos'],focus4:['Relaciones causa-consecuencia y continuidad-cambio','Problemas de la sociedad contemporánea','Economía, ciudadanía y participación','Contraste de fuentes y argumentación histórica']},
  ciencias:{name:'Ciencias',icon:'🔬',skills:['Observar y plantear preguntas','Planificar y conducir investigaciones','Procesar y analizar evidencia','Evaluar','Comunicar'],focus3:['Biología: célula, procesos y organismo','Física: ondas, mecánica, energía y electricidad','Química: estructura, reacciones y estequiometría','Diseño experimental y variables'],focus4:['Biología: herencia, evolución y ambiente','Física: modelación y análisis de fenómenos','Química: orgánica y relaciones cuantitativas','Evaluación de evidencia y conclusiones']}
};

const CAPSULES=[
{id:'3l1',grade:3,subject:'lectura',title:'Encontrar evidencia sin releer todo',minutes:7,summary:'Aprende a localizar información explícita usando palabras ancla, correferencias y paráfrasis.',key:['Lee primero la pregunta y detecta qué dato buscas.','Busca palabras ancla y sus equivalentes, no solo coincidencias literales.','Confirma la respuesta con una oración concreta del texto.'],example:'Si la pregunta pide por qué una autora cambió de opinión, ubica primero el momento del cambio y luego la causa explícita o parafraseada.',check:'Antes de marcar una alternativa, pregúntate: ¿puedo señalar la línea o idea exacta que la respalda?'},
{id:'3l2',grade:3,subject:'lectura',title:'Inferir sin inventar',minutes:8,summary:'Interpreta información implícita conectando pistas del texto.',key:['Una inferencia debe estar apoyada por al menos dos pistas.','No agregues información externa que el texto no permite.','Prefiere la alternativa que explica mejor el conjunto, no un detalle aislado.'],example:'Si un personaje evita responder, cambia de tema y muestra incomodidad, puedes inferir resistencia o preocupación; no necesariamente culpa.',check:'¿Tu inferencia se puede justificar solo con el texto?'},
{id:'3m1a',grade:3,subject:'m1',title:'Porcentajes como multiplicadores',minutes:8,summary:'Convierte aumentos y descuentos en factores para resolver más rápido.',key:['Aumentar p% equivale a multiplicar por 1+p/100.','Disminuir p% equivale a multiplicar por 1-p/100.','Dos cambios sucesivos no se suman necesariamente.'],example:'Subir 20% y luego bajar 20%: 1,20×0,80=0,96. El valor final queda 4% bajo el inicial.',check:'¿Estás aplicando el porcentaje sobre el valor correcto?'},
{id:'3m1b',grade:3,subject:'m1',title:'Funciones: leer antes de calcular',minutes:9,summary:'Reconoce variable independiente, dependiente, tasa de cambio e interceptos.',key:['Identifica qué representa cada eje.','Observa tendencia, cortes y unidades.','Traduce el contexto a una relación antes de usar fórmulas.'],example:'En una tarifa con cargo fijo más costo por kilómetro, el intercepto es el cargo fijo y la pendiente es el precio por kilómetro.',check:'¿Tu respuesta tiene sentido con las unidades del problema?'},
{id:'3m2',grade:3,subject:'m2',title:'Modelar un problema',minutes:10,summary:'Transforma una situación en variables, relaciones y restricciones.',key:['Define variables con significado.','Escribe las condiciones antes de resolver.','Comprueba si la solución respeta dominio y contexto.'],example:'Si x es tiempo, una solución negativa puede ser algebraicamente válida pero no válida en el contexto.',check:'¿La solución satisface todas las condiciones originales?'},
{id:'3h1',grade:3,subject:'historia',title:'Leer una fuente histórica',minutes:8,summary:'Analiza autoría, contexto, propósito y evidencia antes de responder.',key:['Distingue lo que la fuente dice de lo que tú sabes.','Considera quién produce la fuente y para quién.','Relaciona la fuente con el proceso histórico preguntado.'],example:'Un discurso político sirve para conocer una posición o intención, pero no necesariamente prueba por sí solo cómo pensaba toda la sociedad.',check:'¿Estás usando la fuente como evidencia y no como verdad absoluta?'},
{id:'3bio',grade:3,subject:'ciencias',title:'Célula: estructura y función',minutes:9,summary:'Relaciona organelos y estructuras celulares con su función en distintos tipos celulares.',key:['La función de una célula condiciona qué estructuras destacan.','Membrana regula intercambio; núcleo contiene información genética; mitocondria participa en obtención de energía.','Compara células procariontes y eucariontes según estructuras presentes.'],example:'Una célula con alta demanda energética suele presentar abundantes mitocondrias.',check:'¿Puedes explicar por qué una estructura es útil para la función de esa célula?'},
{id:'3fis',grade:3,subject:'ciencias',title:'Física: fuerzas y movimiento',minutes:9,summary:'Distingue fuerza, velocidad y aceleración usando evidencia y diagramas simples.',key:['Velocidad constante implica aceleración cero, no necesariamente fuerza cero individual.','La fuerza neta determina el cambio de movimiento.','Define sistema y dirección positiva antes de operar.'],example:'Dos fuerzas opuestas de igual magnitud producen fuerza neta cero.',check:'¿Analizaste la fuerza neta y no una sola fuerza?'},
{id:'3qui',grade:3,subject:'ciencias',title:'Química: ecuaciones y proporciones',minutes:10,summary:'Usa ecuaciones balanceadas como relaciones cuantitativas.',key:['Primero balancea.','Los coeficientes representan proporciones de partículas o moles.','Conserva átomos de cada elemento.'],example:'En 2H₂ + O₂ → 2H₂O, 2 moles de H₂ reaccionan con 1 mol de O₂.',check:'¿La ecuación está balanceada antes de calcular?'},
{id:'3exp',grade:3,subject:'ciencias',title:'Variables en un experimento',minutes:7,summary:'Identifica variable independiente, dependiente y controles.',key:['La independiente es la que se manipula.','La dependiente es el resultado medido.','Las variables de control reducen explicaciones alternativas.'],example:'Para estudiar luz y crecimiento, intensidad luminosa puede ser independiente y crecimiento la dependiente.',check:'¿El diseño permite atribuir el cambio a la variable estudiada?'},
{id:'4l1',grade:4,subject:'lectura',title:'Evaluar argumentos y evidencia',minutes:9,summary:'Distingue tesis, razones, evidencia y supuestos.',key:['Una afirmación fuerte requiere evidencia pertinente.','Distingue correlación de causalidad.','Evalúa si la evidencia realmente apoya la conclusión.'],example:'Que dos variables cambien juntas no demuestra, por sí solo, que una cause la otra.',check:'¿La conclusión excede lo que la evidencia permite afirmar?'},
{id:'4l2',grade:4,subject:'lectura',title:'Comparar dos textos',minutes:10,summary:'Relaciona postura, propósito, evidencia y tono entre fuentes.',key:['Resume cada texto en una oración antes de compararlos.','Busca acuerdo, desacuerdo o diferencia de enfoque.','No confundas tema común con postura común.'],example:'Dos textos pueden hablar de tecnología y educación, pero uno defender su uso y otro advertir riesgos.',check:'¿Tu comparación incluye una relación concreta entre ambos textos?'},
{id:'4m1a',grade:4,subject:'m1',title:'Estadística: interpretar antes de promediar',minutes:9,summary:'Elige medidas de tendencia y dispersión según la información disponible.',key:['La media es sensible a valores extremos.','La mediana describe bien centros con datos asimétricos.','Lee siempre escala, unidades y tamaño de muestra.'],example:'Un ingreso extremadamente alto puede elevar la media sin representar al individuo típico.',check:'¿La medida elegida responde realmente a la pregunta?'},
{id:'4m1b',grade:4,subject:'m1',title:'Probabilidad: contar sin duplicar',minutes:9,summary:'Organiza casos posibles y favorables mediante tablas, árboles o reglas.',key:['Define el espacio muestral.','Verifica si los eventos son independientes o condicionados.','Evita contar dos veces un mismo resultado.'],example:'En dos lanzamientos de moneda, HT y TH son resultados distintos si importa el orden.',check:'¿Todos los resultados del espacio muestral son comparables?'},
{id:'4m2',grade:4,subject:'m2',title:'Suficiencia de datos',minutes:11,summary:'Decide si la información permite responder sin resolver más de lo necesario.',key:['Evalúa cada dato por separado.','Luego evalúa la combinación si ninguno basta.','“Suficiente” significa respuesta única, no necesariamente cálculo completo.'],example:'Para determinar un número, saber que es par no basta; agregar un intervalo pequeño podría volverlo único.',check:'¿Existe más de una respuesta compatible con los datos?'},
{id:'4h1',grade:4,subject:'historia',title:'Causa, consecuencia y continuidad',minutes:9,summary:'Construye explicaciones históricas evitando relaciones simplistas.',key:['Los procesos suelen tener múltiples causas.','Separa detonantes de causas estructurales.','Reconoce elementos que cambian y otros que permanecen.'],example:'Una crisis política puede tener un detonante inmediato y causas económicas o sociales de largo plazo.',check:'¿Tu explicación distingue escalas de tiempo y tipos de causas?'},
{id:'4h2',grade:4,subject:'historia',title:'Ciudadanía y democracia',minutes:8,summary:'Analiza instituciones, participación, derechos y responsabilidades en problemas públicos.',key:['Distingue poderes e instituciones.','Relaciona derechos con mecanismos de protección y participación.','Evalúa argumentos según principios democráticos y evidencia.'],example:'Participar políticamente no se limita a votar: existen organizaciones, deliberación y mecanismos institucionales.',check:'¿Identificaste qué institución o mecanismo corresponde al problema?'},
{id:'4bio',grade:4,subject:'ciencias',title:'Herencia, variación y evolución',minutes:10,summary:'Relaciona información genética, variación heredable y cambios poblacionales.',key:['La selección actúa sobre variación existente.','Evolucionan poblaciones, no individuos por necesidad.','Distingue genotipo, fenotipo y efecto ambiental.'],example:'Una característica ventajosa puede aumentar en frecuencia si mejora éxito reproductivo y es heredable.',check:'¿Estás explicando cambios de frecuencia en poblaciones?'},
{id:'4fis',grade:4,subject:'ciencias',title:'Electricidad: relaciones y modelos',minutes:10,summary:'Interpreta relaciones entre corriente, voltaje, resistencia y circuitos.',key:['Define qué magnitud cambia y qué se mantiene.','Usa relaciones proporcionales con unidades consistentes.','Comprueba resultados con comportamiento físico esperado.'],example:'Manteniendo resistencia, mayor diferencia de potencial implica mayor corriente.',check:'¿Tu resultado es consistente con el tipo de circuito y las magnitudes?'},
{id:'4qui',grade:4,subject:'ciencias',title:'Estequiometría con estrategia',minutes:11,summary:'Resuelve relaciones masa-mol usando una ruta ordenada.',key:['Convierte a moles cuando corresponda.','Usa la proporción de la ecuación balanceada.','Convierte al formato solicitado al final.'],example:'Ruta típica: gramos → moles → razón estequiométrica → moles → gramos.',check:'¿Usaste los coeficientes como razón molar?'},
{id:'4ev',grade:4,subject:'ciencias',title:'Evaluar evidencia científica',minutes:9,summary:'Juzga conclusiones, calidad de datos y limitaciones de una investigación.',key:['Una conclusión debe responder la pregunta investigada.','Considera controles, replicación, muestra e incertidumbre.','No generalices más allá de la población o condiciones estudiadas.'],example:'Un experimento con cinco individuos puede sugerir un patrón, pero limita la fuerza de una generalización amplia.',check:'¿La evidencia es suficiente para la conclusión propuesta?'}
];

function learningState(){return safeParse(localStorage.getItem(scopedKey(LEARN_KEY)),{done:[],last:''})}
function saveLearning(s){localStorage.setItem(scopedKey(LEARN_KEY),JSON.stringify(s))}
function learningAllowed(){return commercialMode==='member'||commercialMode==='trial'}
function learningGate(){if(!learningAllowed()){landing();return false}return true}
function subjectCaps(grade,subject){return CAPSULES.filter(c=>c.grade===grade&&(!subject||c.subject===subject))}
function courseProgress(grade){let s=learningState(),all=subjectCaps(grade);return {done:all.filter(c=>s.done.includes(c.id)).length,total:all.length}}

function learningHub(){if(!learningGate())return;resetState();let p3=courseProgress(3),p4=courseProgress(4);app.innerHTML=`
<h1>🧠 Aprende PAES</h1>
<section class="card" style="border-left:5px solid #2563eb"><div class="eyebrow">RUTA DE APRENDIZAJE</div><h2>Prepárate desde 3° y 4° medio</h2><p>Cápsulas breves, temarios por prueba y progreso conectado a tu racha. La división por curso es una ruta pedagógica de PAES Trainer; los ejes y habilidades se alinean con los temarios DEMRE vigentes.</p><div class="meta"><span class="pill">Revisión DEMRE: ${esc(DEMRE_REVIEW)}</span><span class="pill">Cápsulas completadas: ${learningState().done.length}/${CAPSULES.length}</span></div></section>
<div class="sectionTitle"><div><h2>Elige tu etapa</h2><p>3° medio construye base y hábitos; 4° medio profundiza e integra en formato PAES.</p></div></div>
<section class="grid"><article class="card"><div style="font-size:42px">🌱</div><h2>3° medio</h2><p>Construye fundamentos y empieza a entrenar habilidades PAES con tiempo.</p><p><b>${p3.done}/${p3.total}</b> cápsulas completadas</p><button class="btn" onclick="learningGrade(3)">Entrar a 3° medio</button></article><article class="card"><div style="font-size:42px">🚀</div><h2>4° medio</h2><p>Integra contenidos, afina estrategia y practica decisiones de prueba.</p><p><b>${p4.done}/${p4.total}</b> cápsulas completadas</p><button class="btn" onclick="learningGrade(4)">Entrar a 4° medio</button></article></section>
<div class="sectionTitle"><div><h2>Temario PAES por prueba</h2><p>Consulta qué habilidades y áreas debes dominar.</p></div><button class="secondary" onclick="syllabusHub()">Ver temarios</button></div>
<section class="card"><h3>Cómo usar esta sección</h3><p>1) Revisa el temario de tu prueba. 2) Completa cápsulas. 3) Haz una práctica. 4) Usa el diagnóstico para volver al contenido que más necesitas.</p><p class="tiny">PAES Trainer no es una publicación oficial del DEMRE. Recomendamos contrastar siempre con las publicaciones oficiales vigentes.</p></section>`}

function learningGrade(grade){if(!learningGate())return;let prog=courseProgress(grade),subjects=[...new Set(subjectCaps(grade).map(c=>c.subject))];app.innerHTML=`<div class="toolbar"><button class="ghost" onclick="learningHub()">← Aprende PAES</button><button class="secondary" onclick="syllabusHub(${grade})">Temarios</button></div><h1>${grade===3?'🌱':'🚀'} Ruta ${grade}° medio</h1><section class="card"><h2>${grade===3?'Construye una base PAES sólida':'Integra, practica y sube tu rendimiento'}</h2><p>${grade===3?'La meta es comprender conceptos y desarrollar habilidades antes de intensificar los ensayos.':'La meta es dominar decisiones de prueba, integrar ejes y detectar rápidamente tus brechas.'}</p><div class="xpTrack"><div style="width:${prog.total?Math.round(prog.done/prog.total*100):0}%"></div></div><p><b>${prog.done}/${prog.total}</b> cápsulas completadas</p></section><div class="sectionTitle"><div><h2>Cápsulas por área</h2></div></div>${subjects.map(s=>capsuleSubjectBlock(grade,s)).join('')}`}
function capsuleSubjectBlock(grade,subject){let info=PAES_SYLLABUS[subject],st=learningState(),caps=subjectCaps(grade,subject);return `<section class="card"><div class="sectionTitle"><div><h2>${info.icon} ${esc(info.name)}</h2><p>${grade===3?esc(info.focus3.join(' · ')):esc(info.focus4.join(' · '))}</p></div></div><div class="grid">${caps.map(c=>`<article class="card" style="box-shadow:none;border:1px solid #e2e8f0"><div class="meta"><span class="pill">${c.minutes} min</span>${st.done.includes(c.id)?'<span class="pill">✅ Completada</span>':'<span class="pill">+20 XP</span>'}</div><h3>${esc(c.title)}</h3><p>${esc(c.summary)}</p><button class="${st.done.includes(c.id)?'secondary':'btn'}" onclick="openCapsule('${c.id}')">${st.done.includes(c.id)?'Repasar':'Aprender'}</button></article>`).join('')}</div></section>`}
function openCapsule(id){if(!learningGate())return;let c=CAPSULES.find(x=>x.id===id);if(!c)return;let info=PAES_SYLLABUS[c.subject],done=learningState().done.includes(id);app.innerHTML=`<div class="toolbar"><button class="ghost" onclick="learningGrade(${c.grade})">← Volver</button><span class="pill">${c.minutes} min</span></div><section class="card"><div class="eyebrow">${c.grade}° MEDIO · ${esc(info.name)}</div><h1>${esc(c.title)}</h1><p style="font-size:1.08rem">${esc(c.summary)}</p></section><section class="card"><h2>💡 Qué debes entender</h2><ul>${c.key.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="card" style="border-left:5px solid #f59e0b"><h2>🧩 Ejemplo mental</h2><p>${esc(c.example)}</p></section><section class="card" style="border-left:5px solid #10b981"><h2>✅ Chequeo rápido</h2><p><b>${esc(c.check)}</b></p><p>Si puedes responderlo con seguridad y explicarlo con tus palabras, estás listo para practicar.</p></section><div class="toolbar"><button class="btn" onclick="completeCapsule('${c.id}')">${done?'✅ Repaso completado':'Completar cápsula · +20 XP'}</button><button class="secondary" onclick="practiceSetup()">Ir a práctica</button></div>`}
function completeCapsule(id){let s=learningState(),first=!s.done.includes(id);if(first){s.done.push(id);s.last=new Date().toISOString();saveLearning(s);try{let g=getGame();g.xp+=20;saveGame(g)}catch(e){}}let c=CAPSULES.find(x=>x.id===id);alert(first?'✅ Cápsula completada. Ganaste +20 XP.':'✅ Repaso registrado.');openCapsule(id)}

function syllabusHub(grade){if(!learningGate())return;let subjects=Object.keys(PAES_SYLLABUS);app.innerHTML=`<div class="toolbar"><button class="ghost" onclick="learningHub()">← Aprende PAES</button>${grade?`<button class="secondary" onclick="learningGrade(${grade})">Ruta ${grade}°</button>`:''}</div><h1>📋 Temarios de estudio PAES</h1><section class="card"><div class="eyebrow">ALINEACIÓN DEMRE</div><h2>Qué preparar para las pruebas</h2><p>Esta guía resume ejes y habilidades para organizar tu estudio. La PAES evalúa conocimientos acumulados a lo largo de la trayectoria escolar; la separación 3°/4° es una propuesta de planificación de PAES Trainer y no una división oficial del DEMRE.</p><div class="meta"><span class="pill">${esc(DEMRE_REVIEW)}</span></div></section>${subjects.map(s=>syllabusCard(s,grade)).join('')}<section class="card"><h3>Fuente oficial</h3><p>DEMRE es la referencia oficial para temarios, estructura y cambios del proceso de admisión. Esta sección debe actualizarse cuando DEMRE publique modificaciones.</p><a class="secondary" style="display:inline-block;text-decoration:none" href="${DEMRE_URL}" target="_blank" rel="noopener">Consultar DEMRE</a></section>`}
function syllabusCard(subject,grade){let i=PAES_SYLLABUS[subject],focus=grade===3?i.focus3:grade===4?i.focus4:[...i.focus3,...i.focus4];return `<section class="card"><div class="sectionTitle"><div><h2>${i.icon} ${esc(i.name)}</h2><p>${grade?`Ruta sugerida para ${grade}° medio`:'Mapa general de preparación'}</p></div><button class="secondary" onclick="learningGrade(${grade||4})">Ver cápsulas</button></div><div class="grid"><div><h3>Habilidades</h3><ul>${i.skills.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div><h3>${grade?'Prioridades de esta etapa':'Contenidos y focos'}</h3><ul>${[...new Set(focus)].map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div></section>`}


// ===== CLASES PERSONALIZADAS SEGUN DIAGNOSTICO =====
const PERSONAL_CLASS_KEY='paesPersonalClassesV1';
function personalClassState(){return safeParse(localStorage.getItem(scopedKey(PERSONAL_CLASS_KEY)),{done:[],last:''})}
function savePersonalClassState(s){localStorage.setItem(scopedKey(PERSONAL_CLASS_KEY),JSON.stringify(s))}
function personalSkillStats(){let h=getHistory(),skills={};h.forEach(r=>Object.entries(r.skills||{}).forEach(([k,v])=>{skills[k]??={ok:0,n:0};skills[k].ok+=v.ok;skills[k].n+=v.n}));return Object.entries(skills).map(([skill,v])=>({skill,ok:v.ok,n:v.n,p:pct(v.ok,v.n)})).sort((a,b)=>a.p-b.p)}
function classTemplate(skill){let x=String(skill||'').toLowerCase();
 const t=(title,goal,theory,steps,example,q,opts,correct,tip)=>({title,goal,theory,steps,example,q,opts,correct,tip});
 if(/localiz|lectura|infer|interpret|evaluar|argument|texto/.test(x))return t('Leer con evidencia','Responder desde el texto y no desde intuiciones externas.','En Competencia Lectora, una alternativa correcta debe poder justificarse con información explícita o con una inferencia sostenida por pistas del texto.',['Identifica exactamente qué pide la pregunta.','Ubica la zona del texto relacionada.','Descarta alternativas que agregan información no demostrada.','Antes de marcar, formula tu evidencia en una frase.'],'Si el texto dice que una medida fue criticada por su costo, no puedes concluir que fracasó, salvo que el texto entregue evidencia de fracaso.','¿Qué hace más sólida una inferencia?',['Que parezca razonable','Que esté apoyada por pistas del texto','Que coincida con mi experiencia'],1,'Subraya mentalmente dos pistas antes de responder preguntas inferenciales.');
 if(/func|algebra|ecuac|modelo/.test(x))return t('Álgebra y funciones con sentido','Traducir el contexto a relaciones matemáticas antes de operar.','La clave no es memorizar más fórmulas, sino identificar variables, relaciones y restricciones. Una función conecta una variable de entrada con una salida siguiendo una regla.',['Define qué representa cada variable.','Identifica qué cambia y qué permanece fijo.','Construye la relación o ecuación.','Comprueba la solución en el contexto.'],'Una tarifa de $2.000 más $500 por kilómetro se modela como C(x)=2000+500x. El 2000 es cargo fijo y 500 es la tasa de cambio.','En C(x)=3000+700x, ¿qué representa 700?',['El costo inicial','El costo por unidad de x','La cantidad total'],1,'Siempre interpreta pendiente e intercepto con sus unidades.');
 if(/prob|estad|datos|azar/.test(x))return t('Probabilidad y datos','Organizar casos y elegir medidas estadísticas según la pregunta.','En probabilidad debes construir correctamente el espacio muestral; en estadística debes decidir qué medida representa mejor los datos y leer escalas/unidades.',['Define los casos posibles.','Evita duplicar resultados.','Distingue media, mediana y dispersión.','Comprueba si hay valores extremos.'],'En datos muy asimétricos por un valor extremadamente alto, la mediana suele representar mejor el centro que la media.','¿Qué medida suele ser más resistente a valores extremos?',['Media','Mediana','Rango'],1,'Antes de calcular, pregunta qué información realmente necesitas comparar.');
 if(/geometr|medic|espacio/.test(x))return t('Geometría sin perder el contexto','Relacionar figuras, medidas y transformaciones con propiedades.','La geometría PAES exige reconocer propiedades antes de aplicar fórmulas. Dibujar, marcar datos y cuidar unidades evita muchos errores.',['Haz un esquema.','Marca datos conocidos y lo pedido.','Elige la propiedad o relación pertinente.','Revisa unidades y orden de magnitud.'],'Si duplicas todas las longitudes de una figura semejante, el área se multiplica por 4, no por 2.','Si el factor de escala lineal es 3, ¿por cuánto se multiplica el área?',['3','6','9'],2,'Distingue siempre entre factores lineales, de área y de volumen.');
 if(/número|numero|porcent|propor|razón|razon/.test(x))return t('Números, razones y porcentajes','Resolver cambios y comparaciones usando multiplicadores y proporciones.','Los porcentajes describen una proporción respecto de una base. En cambios sucesivos, cada porcentaje se aplica sobre el valor vigente, no sobre el inicial.',['Identifica la base del porcentaje.','Convierte el porcentaje a factor cuando convenga.','Aplica los cambios en orden.','Comprueba si el resultado esperado debe subir o bajar.'],'Aumentar 20% y luego bajar 20% equivale a multiplicar por 1,2×0,8=0,96.','¿Un aumento de 10% seguido de una baja de 10% vuelve al valor inicial?',['Sí','No','Solo si el valor inicial es 100'],1,'Usa factores 1+p y 1-p para cambios porcentuales sucesivos.');
 if(/fuente|histori|ciudad|econom|temporal|social/.test(x))return t('Historia: evidencia, contexto y procesos','Usar fuentes y conceptos para explicar procesos, no solo recordar datos.','Una fuente histórica debe analizarse considerando autoría, contexto, propósito y alcance. Las preguntas suelen exigir relaciones de causa, consecuencia, continuidad o cambio.',['Identifica autor y contexto.','Distingue lo que la fuente afirma de lo que tú sabes.','Relaciona la evidencia con el proceso histórico.','Evalúa si la conclusión excede lo que la fuente permite.'],'Un discurso político prueba la postura del emisor, pero no necesariamente representa la opinión de toda la sociedad.','¿Qué debes preguntar primero al analizar una fuente?',['Quién la produjo y en qué contexto','Si estoy de acuerdo','Si es larga o corta'],0,'Piensa siempre: autor, contexto, propósito, evidencia.');
 if(/cél|celul|genet|herencia|evolu|biolog|ecosist/.test(x))return t('Biología: relacionar estructura, función y evidencia','Explicar fenómenos biológicos conectando mecanismos y resultados.','En Biología PAES importa establecer relaciones: estructura-función, información genética-fenotipo, organismo-ambiente y evidencia-conclusión.',['Define el nivel biológico involucrado.','Identifica el mecanismo.','Predice qué cambia si una variable se modifica.','Contrasta con la evidencia disponible.'],'Una célula con alta demanda energética suele presentar muchas mitocondrias porque necesita producir más ATP.','¿Qué relación es más útil para explicar una estructura celular?',['Su color','Su función','Su nombre'],1,'Cuando estudies una estructura, pregunta siempre qué función permite realizar.');
 if(/fís|fis|fuerza|mov|onda|electric|energ/.test(x))return t('Física: modelos y relaciones','Interpretar fenómenos mediante magnitudes, relaciones y evidencia.','En Física es clave distinguir magnitudes y analizar cómo se relacionan. Una ecuación sirve si antes entiendes qué representa cada variable y qué condiciones se mantienen.',['Define sistema y variables.','Establece dirección o referencia cuando corresponda.','Usa unidades consistentes.','Comprueba si el resultado tiene sentido físico.'],'Velocidad constante implica aceleración cero. Eso significa fuerza neta cero, aunque puedan existir fuerzas individuales equilibradas.','Si la fuerza neta sobre un cuerpo es cero, su aceleración es:',['Siempre positiva','Cero','Siempre negativa'],1,'Antes de calcular, describe cualitativamente qué debería ocurrir.');
 if(/quím|quim|estequ|reacción|reaccion|mol|átom|atom/.test(x))return t('Química: relaciones cuantitativas','Conectar partículas, moles, ecuaciones y cantidades.','Las ecuaciones químicas balanceadas expresan proporciones entre sustancias. El método más seguro es convertir al nivel adecuado, aplicar la relación y volver a la unidad solicitada.',['Balancea la ecuación.','Convierte a moles si corresponde.','Usa la razón estequiométrica.','Convierte al formato final y revisa unidades.'],'En 2H₂ + O₂ → 2H₂O, la razón molar H₂:O₂ es 2:1.','¿Qué representan los coeficientes de una ecuación balanceada?',['Razones molares','Masas atómicas','Temperaturas'],0,'No hagas estequiometría con una ecuación sin balancear.');
 if(/evidencia|investig|variable|experim|cientí|cienti/.test(x))return t('Pensamiento científico','Evaluar diseños, variables y conclusiones a partir de evidencia.','Las preguntas científicas PAES suelen pedir identificar variables, evaluar diseños y determinar si una conclusión está respaldada por los datos.',['Identifica variable independiente y dependiente.','Revisa controles y tamaño de muestra.','Distingue resultado observado de explicación.','Limita la conclusión a lo que los datos permiten.'],'Si un experimento usa solo cinco individuos, puede sugerir un patrón, pero su capacidad de generalización es limitada.','¿Qué fortalece una conclusión experimental?',['Más controles y replicación','Menos mediciones','Eliminar el grupo control'],0,'Pregunta siempre si existe una explicación alternativa que el diseño no controla.');
 return t('Estrategia de resolución PAES','Mejorar precisión usando un proceso de cuatro pasos.','Cuando un eje aún no tiene una cápsula específica, conviene entrenar una estrategia transversal: comprender, representar, resolver y comprobar.',['Resume el problema con tus palabras.','Identifica datos y lo que se pide.','Elige una estrategia justificable.','Comprueba la respuesta con el contexto.'],'Una respuesta numérica puede estar bien calculada y aun así ser incorrecta si no satisface una restricción del problema.','¿Cuál es el último paso antes de marcar una alternativa?',['Comprobar que responde lo pedido','Elegir la opción más larga','Cambiar el resultado'],0,'Después de resolver, vuelve a leer exactamente qué pedía la pregunta.');}
function personalizedClasses(){if(!learningGate())return;resetState();let stats=personalSkillStats();if(!stats.length){app.innerHTML=`<h1>🎓 Mi clase personalizada</h1><section class="card empty"><h2>Primero necesitamos conocerte</h2><p>Completa al menos una práctica o ensayo. Con esos resultados PAES Trainer detectará tus áreas más bajas y preparará clases de refuerzo.</p><button class="btn" onclick="practiceSetup()">Hacer práctica diagnóstica</button><button class="secondary" onclick="learningHub()">Ver cápsulas</button></section>`;return}let st=personalClassState(),top=stats.slice(0,3);app.innerHTML=`<h1>🎓 Clases personalizadas</h1><section class="card" style="border-left:5px solid #7c3aed"><div class="eyebrow">CREADAS DESDE TU DIAGNÓSTICO</div><h2>Tu profesor de refuerzo dentro de PAES Trainer</h2><p>Estas clases se ordenan automáticamente desde tu porcentaje más bajo. Cada clase trabaja una idea central, un ejemplo guiado, una estrategia y un chequeo final.</p></section><div class="sectionTitle"><div><h2>Prioridades de hoy</h2><p>Empieza por la primera y luego vuelve a practicar.</p></div></div><section class="grid three">${top.map((x,i)=>{let tpl=classTemplate(x.skill),id=encodeURIComponent(x.skill),done=st.done.includes(x.skill);return `<article class="card"><div style="font-size:34px">${i===0?'🎯':i===1?'🛠️':'📚'}</div><div class="meta"><span class="pill">${x.p}% dominio</span>${done?'<span class="pill">✅ Vista</span>':'<span class="pill">+60 XP</span>'}</div><h3>${esc(x.skill)}</h3><p>${esc(tpl.goal)}</p><button class="${i===0?'btn':'secondary'}" onclick="openPersonalizedClass('${id}')">${done?'Repasar clase':'Comenzar clase'}</button></article>`}).join('')}</section><section class="card"><h3>Cómo mejora tu clase</h3><p>Después de completar la clase, realiza una práctica. El diagnóstico se recalcula y la próxima clase priorizará lo que siga más bajo.</p><button class="secondary" onclick="diagnostic()">Ver diagnóstico completo</button></section>`}
function openPersonalizedClass(encoded){if(!learningGate())return;let skill=decodeURIComponent(encoded),x=personalSkillStats().find(v=>v.skill===skill),tpl=classTemplate(skill),done=personalClassState().done.includes(skill);app.innerHTML=`<div class="toolbar"><button class="ghost" onclick="personalizedClasses()">← Mis clases</button><span class="pill">${x?x.p+'% actual':'Refuerzo'}</span></div><section class="card" style="border-left:5px solid #7c3aed"><div class="eyebrow">CLASE PERSONALIZADA</div><h1>${esc(tpl.title)}</h1><h3>Área detectada: ${esc(skill)}</h3><p>${esc(tpl.goal)}</p></section><section class="card"><h2>1. Entiende la idea</h2><p>${esc(tpl.theory)}</p></section><section class="card"><h2>2. Método paso a paso</h2><ol>${tpl.steps.map(z=>`<li>${esc(z)}</li>`).join('')}</ol></section><section class="card" style="border-left:5px solid #f59e0b"><h2>3. Ejemplo guiado</h2><p>${esc(tpl.example)}</p><p class="tiny"><b>Consejo:</b> ${esc(tpl.tip)}</p></section><section class="card"><h2>4. Mini chequeo</h2><p><b>${esc(tpl.q)}</b></p><div class="optionList">${tpl.opts.map((o,i)=>`<button class="secondary full" style="margin:.35rem 0;text-align:left" onclick="checkPersonalClass('${encodeURIComponent(skill)}',${i})">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div><div id="personalClassFeedback"></div></section><div class="toolbar"><button class="btn" onclick="completePersonalizedClass('${encodeURIComponent(skill)}')">${done?'✅ Clase repasada':'Completar clase · +60 XP'}</button><button class="secondary" onclick="practiceSetup()">Practicar ahora</button></div>`;window.scrollTo(0,0)}
function checkPersonalClass(encoded,ans){let skill=decodeURIComponent(encoded),tpl=classTemplate(skill),box=document.getElementById('personalClassFeedback');if(!box)return;box.innerHTML=ans===tpl.correct?`<div class="recommend"><strong>✅ Correcto</strong>Aplicaste la idea central de esta clase. Ahora consolídala con práctica.</div>`:`<div class="recommend"><strong>🟡 Todavía no</strong>Revisa el método paso a paso. Pista: ${esc(tpl.tip)}</div>`}
function completePersonalizedClass(encoded){let skill=decodeURIComponent(encoded),s=personalClassState(),first=!s.done.includes(skill);if(first){s.done.push(skill);s.last=new Date().toISOString();savePersonalClassState(s);try{let g=getGame();g.xp+=60;saveGame(g)}catch(e){}}alert(first?'🎓 Clase completada. Ganaste +60 XP. Ahora realiza una práctica para medir si mejoraste.':'✅ Repaso de clase registrado.');personalizedClasses()}
