// PAES Trainer - Pedagogia V2: explicaciones breves, pistas progresivas y videos DEMRE.
// Las preguntas son originales de PAES Trainer; DEMRE se usa como referencia de temarios, habilidades y formato.
const PAES_PEDAGOGY_VERSION='2026-08-18';
const DEMRE_VIDEO={
  lectura:{title:'DEMRE - Pregunta comentada Competencia Lectora',url:'https://www.youtube.com/watch?v=X9oNzfVWLRk'},
  numeros:{title:'DEMRE - Pregunta comentada Competencia Matemática 1',url:'https://www.youtube.com/watch?v=ZcKwZeAt5VA'},
  algebra:{title:'DEMRE - Pregunta comentada M1, capítulo 2',url:'https://www.youtube.com/watch?v=KyLr9MqNTH4'},
  geometria:{title:'DEMRE - Pregunta comentada Competencia Matemática 1',url:'https://www.youtube.com/watch?v=ZcKwZeAt5VA'},
  datos:{title:'DEMRE - Pregunta comentada Competencia Matemática 1',url:'https://www.youtube.com/watch?v=KyLr9MqNTH4'},
  historia:{title:'DEMRE - Pregunta comentada Historia y Ciencias Sociales',url:'https://www.youtube.com/watch?v=UIUP5hNxKvo'},
  biologia:{title:'DEMRE - Pregunta comentada Ciencias Biología',url:'https://www.youtube.com/watch?v=jFUjQDyGXDQ'},
  fisica:{title:'DEMRE - Pregunta comentada Ciencias Física',url:'https://www.youtube.com/watch?v=4Q-qGNkCVHo'},
  quimica:{title:'Canal DEMRE - preguntas comentadas de Ciencias',url:'https://www.youtube.com/@DEMREuchile'},
  ciencia:{title:'Canal DEMRE - preguntas comentadas de Ciencias',url:'https://www.youtube.com/@DEMREuchile'},
  estrategia:{title:'Canal oficial DEMRE',url:'https://www.youtube.com/@DEMREuchile'}
};

const EASY_EXPLAIN={
 lectura:{quick:'Busca evidencia, no intuición. La respuesta correcta debe poder apuntarse con el dedo en el texto o inferirse con pistas claras.',easy:'Piensa que el texto es un testigo. Tú no puedes agregar cosas que el testigo nunca dijo. Primero pregunta: ¿qué parte del texto me permite defender esta respuesta? Si no encuentras evidencia, desconfía.',deep:['Lee primero qué te piden: encontrar, interpretar o evaluar.','Vuelve solo al fragmento necesario.','Di con tus palabras qué debería responderse antes de mirar las alternativas.','Elimina opciones que exageran, cambian el tema o agregan información externa.']},
 numeros:{quick:'Antes de calcular, identifica el total y qué parte de ese total estás buscando.',easy:'Si una pizza tiene 8 trozos y comes 2, comiste 2 de 8. Los porcentajes funcionan igual: siempre preguntan qué parte corresponde respecto de un total. Primero encuentra el total; después la parte.',deep:['Escribe qué cantidad es el 100%.','Traduce el porcentaje a fracción, decimal o factor.','Haz la operación con unidades.','Pregunta si el resultado tiene un tamaño razonable.']},
 algebra:{quick:'Ponle nombre a lo que no conoces y transforma cada frase en una relación.',easy:'Imagina una máquina: entra un número y sale otro. Una función te dice qué hace la máquina. Si cobra $2.000 fijo más $500 por cada kilómetro, el fijo no cambia y los $500 se repiten por cada kilómetro.',deep:['Define la variable: qué representa x.','Separa valor inicial y cambio por unidad.','Escribe la ecuación o función.','Resuelve y vuelve al contexto para interpretar.']},
 geometria:{quick:'Dibuja, marca los datos y recién después elige una fórmula.',easy:'La figura es como un mapa. Si no marcas dónde está cada medida, es fácil perderse. Área es lo que cabe dentro; perímetro es la vuelta por el borde.',deep:['Haz un esquema.','Marca medidas y unidades.','Identifica la propiedad que conecta los datos.','Calcula y revisa si la respuesta tiene sentido visual.']},
 datos:{quick:'Primero entiende qué representan los datos; después calcula.',easy:'La media es como repartir todo en partes iguales. La mediana es la persona que queda justo al medio cuando todos se ordenan. No responden exactamente la misma pregunta.',deep:['Identifica variable y muestra.','Mira escala y unidades.','Elige media, mediana, probabilidad u otra medida según lo preguntado.','Interpreta el número en palabras.']},
 historia:{quick:'Ubica época, fuente y proceso. Después pregunta qué evidencia aporta realmente.',easy:'Una fuente histórica es como escuchar a una persona contar lo que vio: sirve mucho, pero no significa que esa persona represente a todo el país. Hay que mirar quién habla, cuándo y para qué.',deep:['Ubica tiempo y espacio.','Identifica autor y propósito de la fuente.','Extrae una evidencia concreta.','Relaciona esa evidencia con el proceso histórico sin exagerar su alcance.']},
 biologia:{quick:'Relaciona estructura → función → efecto.',easy:'Piensa en una célula como una ciudad: cada parte tiene un trabajo. Si una parte falla, pregunta qué trabajo deja de hacerse y qué consecuencia produce.',deep:['Identifica el nivel: célula, organismo, población o ecosistema.','Reconoce qué estructura o proceso cambia.','Predice el efecto directo.','Contrasta la predicción con los datos.']},
 fisica:{quick:'Dibuja la situación y separa qué conoces de qué buscas.',easy:'La física cuenta una historia de cambios. Si empujas un carro, pregunta qué fuerza actúa, hacia dónde y qué cambia: su rapidez, dirección o energía.',deep:['Haz un esquema.','Define magnitudes y unidades.','Elige la relación física adecuada.','Calcula y comprueba signo, dirección y orden de magnitud.']},
 quimica:{quick:'Cuenta partículas o moles antes de hacer proporciones.',easy:'Una ecuación química se parece a una receta. Si la receta pide 2 tazas de harina por 1 de leche, no puedes cambiar esa proporción sin cambiar el resultado. Los coeficientes químicos cumplen ese papel.',deep:['Balancea o lee correctamente la ecuación.','Identifica la proporción entre sustancias.','Convierte unidades si es necesario.','Comprueba conservación y coherencia.']},
 ciencia:{quick:'Pregunta qué variable se cambia, cuál se mide y qué evidencia permitiría concluir algo.',easy:'Un experimento justo cambia una cosa a la vez. Si cambias temperatura y cantidad de agua al mismo tiempo, después no sabes cuál de las dos causó el resultado.',deep:['Identifica pregunta o hipótesis.','Separa variable independiente, dependiente y controles.','Mira si los datos realmente apoyan la conclusión.','Distingue correlación de causalidad.']},
 estrategia:{quick:'Traduce la pregunta a una tarea concreta y elimina distractores uno por uno.',easy:'No necesitas saber todo de inmediato. Pregúntate: ¿qué me están pidiendo exactamente?, ¿qué información sí sirve?, ¿qué alternativas puedo descartar sin calcular todo?',deep:['Subraya la acción pedida.','Selecciona datos relevantes.','Anticipa una respuesta.','Compara alternativas y verifica.']}
};
function pedagogicPack(skill){return EASY_EXPLAIN[classCategory(skill)]||EASY_EXPLAIN.estrategia}
function classVideo(skill){return DEMRE_VIDEO[classCategory(skill)]||DEMRE_VIDEO.estrategia}
function openTeacherVideo(skill){const v=classVideo(skill);window.open(v.url,'_blank','noopener,noreferrer')}
function cleanQuestionText(q){return String((q&&q.text)||'').replace(/\s+/g,' ').trim()}
function qnums(q){return (cleanQuestionText(q).match(/-?\d+(?:[.,]\d+)?/g)||[]).slice(0,5)}
function hasAny(s,arr){s=s.toLowerCase();return arr.some(x=>s.includes(x))}
function shortFocus(q){
  const stop=new Set('cual cuales que como cuanto cuantos cuanta cuantas para entre desde tiene tienen una uno unos unas del las los por con sin sobre segun entonces igual aproximadamente siguiente siguientes corresponde principal principalmente puede pueden esta este estas estos donde cuando'.split(' '));
  return cleanQuestionText(q).toLowerCase().replace(/[^a-záéíóúñ0-9%$ ]/gi,' ').split(/\s+/).filter(w=>w.length>3&&!stop.has(w)).slice(0,6).join(', ')
}
function specificHint(q){
  const t=cleanQuestionText(q), l=t.toLowerCase(), ns=qnums(q), skill=String(q.skill||'');
  if(/%|porcentaje/.test(l)) return ns.length>=2?`Fíjate en los dos datos clave de ESTA pregunta: ${ns[0]}% y ${ns[1]}. Convierte el porcentaje a una parte de 100 y aplícalo al total. Todavía no mires las alternativas.`:`Identifica qué cantidad representa el 100% y qué porcentaje te piden calcular.`;
  if(/precio es proporcional|cuestan/.test(l)&&/objet/.test(l)) return ns.length>=3?`Aquí hay una proporción directa. Con los datos ${ns[0]} objetos y $${ns[1]} mil, encuentra primero el valor de 1 objeto. Luego llévalo a ${ns[2]} objetos.`:`Encuentra primero el valor de una unidad y después escala a la cantidad pedida.`;
  if(/f\(x\)|función|funcion/.test(l)&&/f\(/.test(l)) return ns.length?`Esta pregunta pide evaluar una función. Reemplaza x por el valor indicado (${ns[ns.length-1]}) respetando signos y orden de operaciones.`:`Sustituye el valor indicado de x en la expresión antes de operar.`;
  if(/\bx\b/.test(l)&&/=/.test(t)) return `Primero resuelve la ecuación que aparece en el enunciado para encontrar x. Recién después usa ese valor en la segunda expresión que te preguntan.`;
  if(/máximo común divisor|maximo comun divisor|mcd/.test(l)) return ns.length>=2?`Busca el mayor número que divide exactamente a ${ns[0]} y ${ns[1]}. Puedes listar divisores o descomponer ambos en factores primos.`:`Busca los factores que ambos números comparten y quédate con la combinación más grande.`;
  if(/circunferencia|círculo|circulo/.test(l)&&/radio/.test(l)) return ns.length?`No confundas área con perímetro. Como te dan radio ${ns[0]} cm, necesitas la fórmula del área: π·r². Primero eleva el radio al cuadrado.`:`Te piden lo que cubre el interior del círculo: usa área, no la longitud del borde.`;
  if(/triángulo rectángulo|triangulo rectangulo/.test(l)&&/hipotenusa/.test(l)) return ns.length>=2?`Los catetos de esta pregunta son ${ns[0]} y ${ns[1]}. Usa Pitágoras: hipotenusa² = cateto² + cateto². No sumes los catetos directamente.`:`Dibuja el triángulo y recuerda que la hipotenusa es el lado opuesto al ángulo recto.`;
  if(/probabilidad/.test(l)&&/(fichas|bolsa|rojas|extraer)/.test(l)) return ns.length>=2?`Cuenta casos favorables y casos posibles con los datos de esta bolsa: ${ns.join(' y ')}. La probabilidad parte como favorables / total; después simplifica.`:`Piensa: “de todas las fichas, ¿cuántas me sirven?”. Ese número va arriba; el total va abajo.`;
  if(/promedio|media/.test(l)) return `Suma SOLO los datos que aparecen en esta pregunta y divide por la cantidad de datos. Antes de dividir, cuenta cuántos valores hay.`;
  if(/mediana/.test(l)) return `Ordena los datos de menor a mayor. La mediana depende de la posición central, no de sumar todos los valores.`;
  if(/frecuencia/.test(l)&&/longitud de onda/.test(l)) return `La pregunta mantiene constante la rapidez. Usa la relación v = f·λ y piensa: si f aumenta mientras v no cambia, ¿qué debe pasar con λ?`;
  if(/velocidad constante/.test(l)&&/fuerza neta/.test(l)) return `“Velocidad constante” significa que la aceleración es cero. Relaciona esa idea con F = m·a antes de elegir.`;
  if(/variable independiente/.test(l)||(/experimento/.test(l)&&/mide/.test(l))) return `Separa dos cosas de ESTE experimento: qué factor cambia el investigador y qué resultado observa/mide. El que se cambia a propósito es la variable independiente.`;
  if(/fuente|historiador|decreto|carta|tabla/.test(l)&&/histori/.test((skill+' '+l).toLowerCase())) return `No busques “la respuesta histórica general”. Mira qué tipo de fuente aparece aquí, quién podría producirla y qué información permite sostener sin exagerar.`;
  if(/sintesis de prote|síntesis de prote/.test(l)) return `Piensa en qué estructura celular “arma” proteínas leyendo la información del ARN. Descarta organelos cuya función principal sea digestión, soporte o división celular.`;
  if(/fotosíntesis|fotosintesis/.test(l)) return `Sigue la transformación de energía: la luz entra al sistema. Pregúntate en qué forma queda almacenada esa energía al final del proceso.`;
  if(/número atómico|numero atomico/.test(l)) return `No mezcles número atómico con masa atómica. El número atómico identifica al elemento por una partícula específica del núcleo.`;
  if(/reacción química balanceada|reaccion quimica balanceada/.test(l)) return `Una ecuación balanceada funciona como una contabilidad de átomos: cuenta cada elemento antes y después y busca qué magnitud debe conservarse.`;
  if(q._context) return `Vuelve al texto asociado y busca la evidencia exacta para “${t.slice(0,90)}${t.length>90?'…':''}”. Antes de mirar alternativas, responde con tus propias palabras en una frase.`;
  return `En esta pregunta concéntrate en: ${shortFocus(q)||skill||'la relación central del enunciado'}. Decide primero qué concepto conecta esos datos antes de mirar las alternativas.`;
}
function specificEasy(q){
  const t=cleanQuestionText(q), l=t.toLowerCase(), ns=qnums(q), p=pedagogicPack(q.skill);
  if(/%|porcentaje/.test(l)) return ns.length>=2?`🍎 Imagínalo como una bolsa de 100 partes. ${ns[0]}% significa tomar ${ns[0]} de esas 100 partes. Aquí el “paquete completo” vale ${ns[1]}; calcula cuánto corresponde a esa fracción del total. Hazlo como: total × ${ns[0]} ÷ 100.`:p.easy;
  if(/precio es proporcional|cuestan/.test(l)&&/objet/.test(l)) return ns.length>=3?`🍎 Piensa en repartir $${ns[1]} mil entre ${ns[0]} objetos iguales. Eso te dice cuánto cuesta UNO. Después imagina comprar ${ns[2]} de esos mismos objetos: repites ese precio ${ns[2]} veces.`:p.easy;
  if(/f\(x\)|función|funcion/.test(l)&&/f\(/.test(l)) return `🍎 Una función es como una máquina con una casilla vacía llamada x. Esta pregunta te entrega un número para poner en esa casilla. Sustitúyelo exactamente donde aparece x y después calcula de izquierda a derecha respetando multiplicaciones y signos.`;
  if(/\bx\b/.test(l)&&/=/.test(t)) return `🍎 Tienes una balanza. Primero deja a x sola haciendo la misma operación a ambos lados de la igualdad. Cuando sepas cuánto vale x, recién reemplázala en lo que te preguntan al final. Son DOS pasos, no uno.`;
  if(/máximo común divisor|maximo comun divisor|mcd/.test(l)) return ns.length>=2?`🍎 Imagina que quieres hacer grupos del mismo tamaño usando ${ns[0]} cosas y también ${ns[1]} cosas, sin que sobre nada. Buscas el tamaño de grupo más grande que funcione para ambos números.`:p.easy;
  if(/circunferencia|círculo|circulo/.test(l)&&/radio/.test(l)) return ns.length?`🍎 Si el radio mide ${ns[0]} cm, primero haces ${ns[0]} × ${ns[0]}. Ese resultado se multiplica por π (aprox. 3,14). Eso mide la superficie de adentro del círculo.`:p.easy;
  if(/triángulo rectángulo|triangulo rectangulo/.test(l)&&/hipotenusa/.test(l)) return ns.length>=2?`🍎 Tienes dos lados cortos de ${ns[0]} y ${ns[1]}. Eleva cada uno al cuadrado, súmalos y al final busca qué número al cuadrado da ese total. Ese número es la hipotenusa.`:p.easy;
  if(/probabilidad/.test(l)&&/(fichas|bolsa|rojas|extraer)/.test(l)) return `🍎 Imagina meter la mano a la bolsa con los ojos cerrados. Arriba de la fracción pones cuántas fichas cumplen lo que te piden; abajo pones cuántas fichas hay en total. Luego simplificas la fracción si se puede.`;
  if(/promedio|media/.test(l)) return `🍎 Junta todos los valores como si fueran puntos de un equipo. Súmalos y luego repártelos por igual entre la cantidad de datos. Lo que recibe cada uno es el promedio.`;
  if(/mediana/.test(l)) return `🍎 Ordena a todos en una fila de menor a mayor. La mediana es el que queda justo al centro. Si hay dos al centro, promedias solo esos dos.`;
  if(/frecuencia/.test(l)&&/longitud de onda/.test(l)) return `🍎 Imagina olas que viajan siempre a la misma rapidez. Si ahora pasan más olas cada segundo (más frecuencia), cada ola tiene que ocupar menos espacio; por eso piensa qué ocurre con la distancia entre crestas.`;
  if(/velocidad constante/.test(l)&&/fuerza neta/.test(l)) return `🍎 Si un auto sigue derecho a la misma rapidez, no está acelerando. En F = m·a, si a vale cero, piensa qué ocurre con la fuerza total resultante.`;
  if(/variable independiente/.test(l)||(/experimento/.test(l)&&/mide/.test(l))) return `🍎 En un experimento hay una “perilla” que tú cambias y un “marcador” que observas. La perilla es la variable independiente; el marcador es la dependiente. Busca cuál cumple cada papel en ESTE enunciado.`;
  if(/fuente|historiador|decreto|carta|tabla/.test(l)) return `🍎 Trata la fuente como un mensaje de WhatsApp antiguo: primero pregunta quién lo escribió, cuándo y para qué. Sirve como evidencia, pero no significa automáticamente que represente a todas las personas o pruebe una causa.`;
  if(/sintesis de prote|síntesis de prote/.test(l)) return `🍎 Piensa en una fábrica celular. Hay una estructura que funciona como la “máquina armadora”: toma instrucciones y une aminoácidos para construir proteínas. Busca esa función entre las alternativas.`;
  if(/fotosíntesis|fotosintesis/.test(l)) return `🍎 La planta recibe luz como “energía de entrada” y la guarda en alimento. Pregúntate qué tipo de energía queda almacenada en esas moléculas orgánicas.`;
  if(/número atómico|numero atomico/.test(l)) return `🍎 Cada elemento tiene un “número de carnet”. Ese número depende de cuántos protones hay en el núcleo. No lo confundas con protones + neutrones, que se relaciona con la masa.`;
  if(/reacción química balanceada|reaccion quimica balanceada/.test(l)) return `🍎 Piensa en piezas de LEGO: puedes reordenarlas para formar algo nuevo, pero no deberían aparecer ni desaparecer piezas. Una ecuación balanceada muestra justamente esa conservación.`;
  if(q._context) return `🍎 Lee el texto como detective. La pregunta dice: “${t.slice(0,105)}${t.length>105?'…':''}”. Busca una o dos frases del texto que respondan directamente eso. No uses lo que tú sabes del tema si el texto no lo dice o no permite inferirlo.`;
  return `🍎 Esta pregunta trata específicamente de ${shortFocus(q)||q.skill||'este contenido'}. Tradúcela a una tarea pequeña: ¿qué dato tengo?, ¿qué debo descubrir?, ¿qué relación del tema conecta ambas cosas? Resuélvela en ese orden.`;
}
function questionHint(q,level){if(level===1)return specificHint(q);if(level===2)return specificEasy(q);const p=pedagogicPack(q.skill);return `Hazlo en este orden: ${p.deep.join(' → ')} Después compara tu resultado con las alternativas.`}
function showPedHint(i,level){const el=document.getElementById(`pedhint-${i}`);if(el)el.innerHTML=`<strong>${level===1?'💡 Pista para ESTA pregunta':'🍎 Explícamelo fácil'}</strong><br>${esc(questionHint(preuSession.questions[i],level))}`}

function classQuestionHTML(q,i){return `<section class="question"><div class="meta"><span class="pill">Pregunta ${i+1}/10</span><span class="pill">${esc(q.difficulty||'Media')}</span><span class="pill">${esc(q.skill||'General')}</span></div>${q._context?`<details class="passage" ${i<2?'open':''}><summary><b>Texto para responder</b></summary><p>${esc(q._context)}</p></details>`:''}<h3>${esc(q.text)}</h3>${q.options.map(o=>`<label class="option"><input type="radio" name="pcq${i}" value="${o.key}" onchange="preuAnswer(${i},'${o.key}')"><b>${o.key})</b> ${esc(o.text)}</label>`).join('')}<div class="toolbar" style="margin-top:.7rem"><button class="ghost" onclick="showPedHint(${i},1)">💡 Dame una pista</button><button class="ghost" onclick="showPedHint(${i},2)">🍎 Explícamelo fácil</button></div><div id="pedhint-${i}" class="recommend" style="display:block;margin-top:.5rem">Usa una pista solo si la necesitas. Intenta pensar primero por tu cuenta.</div></section>`}

function openPersonalizedClass(encoded){if(!learningGate())return;const skill=decodeURIComponent(encoded),stat=personalSkillStats().find(v=>v.skill===skill),th=classTheory(skill),qs=chooseClassQuestions(skill,10),p=pedagogicPack(skill),v=classVideo(skill);preuSession={skill,questions:qs,answers:{},started:Date.now()};const g=preuGrade();app.innerHTML=`<div class="toolbar"><button class="ghost" onclick="personalizedClasses()">← Mis clases</button><span class="pill">${g}° Medio</span><span class="pill">${stat?stat.p+'% actual':'Refuerzo'}</span></div><section class="card" style="border-left:5px solid #7c3aed"><div class="eyebrow">CLASE PERSONALIZADA PAES · ${g}° MEDIO</div><h1>${esc(th.title)}</h1><p><b>Tu foco:</b> ${esc(skill)}. ${g===3?'Vamos desde la base y subimos de a poco.':'Vamos directo a comprensión, estrategia y aplicación PAES.'}</p></section><section class="grid three"><article class="card"><h2>⚡ Resumen rápido</h2><p>${esc(p.quick)}</p></article><article class="card" style="border-left:5px solid #f59e0b"><h2>🍎 Explícamelo fácil</h2><p>${esc(p.easy)}</p></article><article class="card" style="border-left:5px solid #7c3aed"><h2>🎓 Aprenderlo bien</h2><ol>${p.deep.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></article></section><section class="card"><h2>▶️ ¿Prefieres verlo?</h2><p>Complementa la clase con una pregunta comentada o material del canal oficial DEMRE.</p><button class="secondary" onclick="openTeacherVideo('${encodeURIComponent(skill)}')">▶️ ${esc(v.title)}</button><p class="tiny">El video se abre en YouTube. Es material externo y complementario; PAES Trainer no copia preguntas oficiales.</p></section><section class="card"><h2>👨‍🏫 Ahora el profesor te muestra el método</h2><p>No memorices una letra. Usa siempre este camino:</p><ol>${th.method.slice(0,5).map(x=>`<li>${esc(x)}</li>`).join('')}</ol><div class="recommend"><strong>Idea clave</strong>${esc(th.tips[0]||p.quick)}</div></section><section class="grid"><article class="card"><h2>✏️ Ejemplo guiado</h2><p><b>1.</b> Lee y di qué te piden con tus palabras.</p><p><b>2.</b> Marca solo la información útil.</p><p><b>3.</b> Elige una estrategia antes de operar.</p><p><b>4.</b> Resuelve y explica por qué tu respuesta tiene sentido.</p></article><article class="card"><h2>🚨 Trampas típicas</h2><ul>${th.tips.slice(0,4).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article></section><div class="sectionTitle"><div><h2>🎯 Desafío PAES · 10 preguntas</h2><p>Preguntas originales de PAES Trainer, organizadas por eje, habilidad y dificultad con referencia a la estructura PAES/DEMRE.</p></div></div>${qs.length?qs.map((q,i)=>classQuestionHTML(q,i)).join(''):'<section class="card"><p>Aún no hay suficientes preguntas asociadas a este eje.</p></section>'}<div class="toolbar"><button class="btn" onclick="finishPreuClass()">Corregir mi clase</button><button class="secondary" onclick="personalizedClasses()">Salir</button></div>`;window.scrollTo(0,0)}
