// PAES Trainer - Pedagogia V2: explicaciones breves, pistas progresivas y videos DEMRE.
// Las preguntas son originales de PAES Trainer; DEMRE se usa como referencia de temarios, habilidades y formato.
const PAES_PEDAGOGY_VERSION='2026-08-18';
const DEMRE_VIDEO={
  lectura:{title:'DEMRE - Pregunta comentada Competencia Lectora',url:'https://www.youtube.com/watch?v=X9oNzfVWLRk'},
  numeros:{title:'DEMRE - Pregunta comentada Competencia Matemática 1',url:'https://www.youtube.com/watch?v=ZcKwZeAt5VA'},
  algebra:{title:'DEMRE - Pregunta comentada M1, capítulo 2',url:'https://www.youtube.com/watch?v=KyLr9MqNTH4'},
  geometria:{title:'DEMRE - Pregunta comentada Competencia Matemática 1',url:'https://www.youtube.com/watch?v=ZcKwZeAt5VA'},
  datos:{title:'DEMRE - Pregunta comentada Competencia Matemática 1',url:'https://www.youtube.com/watch?v=KyLr9MqNTH4'},
  historia:{title:'DEMRE - Pregunta comentada Historia y Ciencias Sociales',url:'https://www.youtube.com/watch?v=UIUP5hNxKvo'},
  biologia:{title:'DEMRE - Pregunta comentada Ciencias Biología',url:'https://www.youtube.com/watch?v=jFUjQDyGXDQ'},
  fisica:{title:'DEMRE - Pregunta comentada Ciencias Física',url:'https://www.youtube.com/watch?v=4Q-qGNkCVHo'},
  quimica:{title:'Canal DEMRE - preguntas comentadas de Ciencias',url:'https://www.youtube.com/@DEMREuchile'},
  ciencia:{title:'Canal DEMRE - preguntas comentadas de Ciencias',url:'https://www.youtube.com/@DEMREuchile'},
  estrategia:{title:'Canal oficial DEMRE',url:'https://www.youtube.com/@DEMREuchile'}
};

const EASY_EXPLAIN={
 lectura:{quick:'Busca evidencia, no intuición. La respuesta correcta debe poder apuntarse con el dedo en el texto o inferirse con pistas claras.',easy:'Piensa que el texto es un testigo. Tú no puedes agregar cosas que el testigo nunca dijo. Primero pregunta: ¿qué parte del texto me permite defender esta respuesta? Si no encuentras evidencia, desconfía.',deep:['Lee primero qué te piden: encontrar, interpretar o evaluar.','Vuelve solo al fragmento necesario.','Di con tus palabras qué debería responderse antes de mirar las alternativas.','Elimina opciones que exageran, cambian el tema o agregan información externa.']},
 numeros:{quick:'Antes de calcular, identifica el total y qué parte de ese total estás buscando.',easy:'Si una pizza tiene 8 trozos y comes 2, comiste 2 de 8. Los porcentajes funcionan igual: siempre preguntan qué parte corresponde respecto de un total. Primero encuentra el total; después la parte.',deep:['Escribe qué cantidad es el 100%.','Traduce el porcentaje a fracción, decimal o factor.','Haz la operación con unidades.','Pregunta si el resultado tiene un tamaño razonable.']},
 algebra:{quick:'Ponle nombre a lo que no conoces y transforma cada frase en una relación.',easy:'Imagina una máquina: entra un número y sale otro. Una función te dice qué hace la máquina. Si cobra $2.000 fijo más $500 por cada kilómetro, el fijo no cambia y los $500 se repiten por cada kilómetro.',deep:['Define la variable: qué representa x.','Separa valor inicial y cambio por unidad.','Escribe la ecuación o función.','Resuelve y vuelve al contexto para interpretar.']},
 geometria:{quick:'Dibuja, marca los datos y recién después elige una fórmula.',easy:'La figura es como un mapa. Si no marcas dónde está cada medida, es fácil perderse. Área es lo que cabe dentro; perímetro es la vuelta por el borde.',deep:['Haz un esquema.','Marca medidas y unidades.','Identifica la propiedad que conecta los datos.','Calcula y revisa si la respuesta tiene sentido visual.']},
 datos:{quick:'Primero entiende qué representan los datos; después calcula.',easy:'La media es como repartir todo en partes iguales. La mediana es la persona que queda justo al medio cuando todos se ordenan. No responden exactamente la misma pregunta.',deep:['Identifica variable y muestra.','Mira escala y unidades.','Elige media, mediana, probabilidad u otra medida según lo preguntado.','Interpreta el número en palabras.']},
 historia:{quick:'Ubica época, fuente y proceso. Después pregunta qué evidencia aporta realmente.',easy:'Una fuente histórica es como escuchar a una persona contar lo que vio: sirve mucho, pero no significa que esa persona represente a todo el país. Hay que mirar quién habla, cuándo y para qué.',deep:['Ubica tiempo y espacio.','Identifica autor y propósito de la fuente.','Extrae una evidencia concreta.','Relaciona esa evidencia con el proceso histórico sin exagerar su alcance.']},
 biologia:{quick:'Relaciona estructura → función → efecto.',easy:'Piensa en una célula como una ciudad: cada parte tiene un trabajo. Si una parte falla, pregunta qué trabajo deja de hacerse y qué consecuencia produce.',deep:['Identifica el nivel: célula, organismo, población o ecosistema.','Reconoce qué estructura o proceso cambia.','Predice el efecto directo.','Contrasta la predicción con los datos.']},
 fisica:{quick:'Dibuja la situación y separa qué conoces de qué buscas.',easy:'La física cuenta una historia de cambios. Si empujas un carro, pregunta qué fuerza actúa, hacia dónde y qué cambia: su rapidez, dirección o energía.',deep:['Haz un esquema.','Define magnitudes y unidades.','Elige la relación física adecuada.','Calcula y comprueba signo, dirección y orden de magnitud.']},
 quimica:{quick:'Cuenta partículas o moles antes de hacer proporciones.',easy:'Una ecuación química se parece a una receta. Si la receta pide 2 tazas de harina por 1 de leche, no puedes cambiar esa proporción sin cambiar el resultado. Los coeficientes químicos cumplen ese papel.',deep:['Balancea o lee correctamente la ecuación.','Identifica la proporción entre sustancias.','Convierte unidades si es necesario.','Comprueba conservación y coherencia.']},
 ciencia:{quick:'Pregunta qué variable se cambia, cuál se mide y qué evidencia permitiría concluir algo.',easy:'Un experimento justo cambia una cosa a la vez. Si cambias temperatura y cantidad de agua al mismo tiempo, después no sabes cuál de las dos causó el resultado.',deep:['Identifica pregunta o hipótesis.','Separa variable independiente, dependiente y controles.','Mira si los datos realmente apoyan la conclusión.','Distingue correlación de causalidad.']},
 estrategia:{quick:'Traduce la pregunta a una tarea concreta y elimina distractores uno por uno.',easy:'No necesitas saber todo de inmediato. Pregúntate: ¿qué me están pidiendo exactamente?, ¿qué información sí sirve?, ¿qué alternativas puedo descartar sin calcular todo?',deep:['Subraya la acción pedida.','Selecciona datos relevantes.','Anticipa una respuesta.','Compara alternativas y verifica.']}
};
function pedagogicPack(skill){return EASY_EXPLAIN[classCategory(skill)]||EASY_EXPLAIN.estrategia}
function classVideo(skill){return DEMRE_VIDEO[classCategory(skill)]||DEMRE_VIDEO.estrategia}
function openTeacherVideo(skill){const v=classVideo(skill);window.open(v.url,'_blank','noopener,noreferrer')}
function questionHint(q,level){const p=pedagogicPack(q.skill);if(level===1)return `Primero no calcules. Pregúntate: “¿qué me están pidiendo exactamente?” Luego identifica solo los datos que sirven.`;if(level===2)return p.easy;return `Hazlo en este orden: ${p.deep.join(' → ')} Después compara tu resultado con las alternativas.`}
function showPedHint(i,level){const el=document.getElementById(`pedhint-${i}`);if(el)el.innerHTML=`<strong>${level===1?'💡 Pista':'🍎 Explícamelo fácil'}</strong><br>${esc(questionHint(preuSession.questions[i],level))}`}

function classQuestionHTML(q,i){return `<section class="question"><div class="meta"><span class="pill">Pregunta ${i+1}/10</span><span class="pill">${esc(q.difficulty||'Media')}</span><span class="pill">${esc(q.skill||'General')}</span></div>${q._context?`<details class="passage" ${i<2?'open':''}><summary><b>Texto para responder</b></summary><p>${esc(q._context)}</p></details>`:''}<h3>${esc(q.text)}</h3>${q.options.map(o=>`<label class="option"><input type="radio" name="pcq${i}" value="${o.key}" onchange="preuAnswer(${i},'${o.key}')"><b>${o.key})</b> ${esc(o.text)}</label>`).join('')}<div class="toolbar" style="margin-top:.7rem"><button class="ghost" onclick="showPedHint(${i},1)">💡 Dame una pista</button><button class="ghost" onclick="showPedHint(${i},2)">🍎 Explícamelo fácil</button></div><div id="pedhint-${i}" class="recommend" style="display:block;margin-top:.5rem">Usa una pista solo si la necesitas. Intenta pensar primero por tu cuenta.</div></section>`}

function openPersonalizedClass(encoded){if(!learningGate())return;const skill=decodeURIComponent(encoded),stat=personalSkillStats().find(v=>v.skill===skill),th=classTheory(skill),qs=chooseClassQuestions(skill,10),p=pedagogicPack(skill),v=classVideo(skill);preuSession={skill,questions:qs,answers:{},started:Date.now()};const g=preuGrade();app.innerHTML=`<div class="toolbar"><button class="ghost" onclick="personalizedClasses()">← Mis clases</button><span class="pill">${g}° Medio</span><span class="pill">${stat?stat.p+'% actual':'Refuerzo'}</span></div><section class="card" style="border-left:5px solid #7c3aed"><div class="eyebrow">CLASE PERSONALIZADA PAES · ${g}° MEDIO</div><h1>${esc(th.title)}</h1><p><b>Tu foco:</b> ${esc(skill)}. ${g===3?'Vamos desde la base y subimos de a poco.':'Vamos directo a comprensión, estrategia y aplicación PAES.'}</p></section><section class="grid three"><article class="card"><h2>⚡ Resumen rápido</h2><p>${esc(p.quick)}</p></article><article class="card" style="border-left:5px solid #f59e0b"><h2>🍎 Explícamelo fácil</h2><p>${esc(p.easy)}</p></article><article class="card" style="border-left:5px solid #7c3aed"><h2>🎓 Aprenderlo bien</h2><ol>${p.deep.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></article></section><section class="card"><h2>▶️ ¿Prefieres verlo?</h2><p>Complementa la clase con una pregunta comentada o material del canal oficial DEMRE.</p><button class="secondary" onclick="openTeacherVideo('${encodeURIComponent(skill)}')">▶️ ${esc(v.title)}</button><p class="tiny">El video se abre en YouTube. Es material externo y complementario; PAES Trainer no copia preguntas oficiales.</p></section><section class="card"><h2>👨‍🏫 Ahora el profesor te muestra el método</h2><p>No memorices una letra. Usa siempre este camino:</p><ol>${th.method.slice(0,5).map(x=>`<li>${esc(x)}</li>`).join('')}</ol><div class="recommend"><strong>Idea clave</strong>${esc(th.tips[0]||p.quick)}</div></section><section class="grid"><article class="card"><h2>✏️ Ejemplo guiado</h2><p><b>1.</b> Lee y di qué te piden con tus palabras.</p><p><b>2.</b> Marca solo la información útil.</p><p><b>3.</b> Elige una estrategia antes de operar.</p><p><b>4.</b> Resuelve y explica por qué tu respuesta tiene sentido.</p></article><article class="card"><h2>🚨 Trampas típicas</h2><ul>${th.tips.slice(0,4).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article></section><div class="sectionTitle"><div><h2>🎯 Desafío PAES · 10 preguntas</h2><p>Preguntas originales de PAES Trainer, organizadas por eje, habilidad y dificultad con referencia a la estructura PAES/DEMRE.</p></div></div>${qs.length?qs.map((q,i)=>classQuestionHTML(q,i)).join(''):'<section class="card"><p>Aún no hay suficientes preguntas asociadas a este eje.</p></section>'}<div class="toolbar"><button class="btn" onclick="finishPreuClass()">Corregir mi clase</button><button class="secondary" onclick="personalizedClasses()">Salir</button></div>`;window.scrollTo(0,0)}
